<?php

$cutemi_taxonomies['cutemi_video_resolution'] = array(
	0  => array(
		'term_id'          => 151993,
		'name'             => '2K',
		'slug'             => 'cutemi-video-resolution-2k',
		'term_group'       => 0,
		'term_taxonomy_id' => 151880,
		'taxonomy'         => 'cutemi_video_resolution',
		'description'      => 'Horizontal resolution of approximately 2000 pixels.',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '75',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	1  => array(
		'term_id'          => 151994,
		'name'             => '4K',
		'slug'             => 'cutemi-video-resolution-4k',
		'term_group'       => 0,
		'term_taxonomy_id' => 151881,
		'taxonomy'         => 'cutemi_video_resolution',
		'description'      => 'Horizontal resolution of approximately 4000 pixels.',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '80',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	2  => array(
		'term_id'          => 151995,
		'name'             => '4K UHD',
		'slug'             => 'cutemi-video-resolution-4k-uhd',
		'term_group'       => 0,
		'term_taxonomy_id' => 151882,
		'taxonomy'         => 'cutemi_video_resolution',
		'description'      => '3840x2160',
		'parent'           => 'cutemi-video-resolution-4k',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '80',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	3  => array(
		'term_id'          => 151996,
		'name'             => '5K',
		'slug'             => 'cutemi-video-resolution-5k',
		'term_group'       => 0,
		'term_taxonomy_id' => 151883,
		'taxonomy'         => 'cutemi_video_resolution',
		'description'      => 'Horizontal resolution of approximately 5000 pixels.',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '85',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	4  => array(
		'term_id'          => 151997,
		'name'             => '6K',
		'slug'             => 'cutemi-video-resolution-6k',
		'term_group'       => 0,
		'term_taxonomy_id' => 151884,
		'taxonomy'         => 'cutemi_video_resolution',
		'description'      => 'Horizontal resolution of approximately 6000 pixels.',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '90',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	5  => array(
		'term_id'          => 151998,
		'name'             => '8K',
		'slug'             => 'cutemi-video-resolution-8k',
		'term_group'       => 0,
		'term_taxonomy_id' => 151885,
		'taxonomy'         => 'cutemi_video_resolution',
		'description'      => 'Horizontal resolution of approximately 8000 pixels.',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '95',
			'image_url'       => '',
			'cutemi_disabled' => '1',
		),
	),
	6  => array(
		'term_id'          => 151999,
		'name'             => 'DCI 4K',
		'slug'             => 'cutemi-video-resolution-dci-4k',
		'term_group'       => 0,
		'term_taxonomy_id' => 151886,
		'taxonomy'         => 'cutemi_video_resolution',
		'description'      => '4096x2160',
		'parent'           => 'cutemi-video-resolution-4k',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '80',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	7  => array(
		'term_id'          => 159153,
		'name'             => 'Full HD',
		'slug'             => 'cutemi-video-resolution-full-hd',
		'term_group'       => 0,
		'term_taxonomy_id' => 159040,
		'taxonomy'         => 'cutemi_video_resolution',
		'description'      => 'Full High Definition (1920x1080)',
		'parent'           => 0,
		'count'            => 2,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)FullHD,(?i)Full-HD,(?i)1080p',
			'priority_sum'    => '70',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	8  => array(
		'term_id'          => 159154,
		'name'             => 'HD',
		'slug'             => 'cutemi-video-resolution-hd',
		'term_group'       => 0,
		'term_taxonomy_id' => 159041,
		'taxonomy'         => 'cutemi_video_resolution',
		'description'      => 'High Definition (1280×720)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => 'HD,(?i)720p,(?i)High Definition',
			'priority_sum'    => '65',
			'image_url'       => '',
			'cutemi_disabled' => '0',
		),
	),
	9  => array(
		'term_id'          => 159184,
		'name'             => 'Low',
		'slug'             => 'cutemi-video-resolution-ld',
		'term_group'       => 0,
		'term_taxonomy_id' => 159071,
		'taxonomy'         => 'cutemi_video_resolution',
		'description'      => 'Up to 360p',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)144p,(?i)240p,(?i)360p',
			'priority_sum'    => '50',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	10 => array(
		'term_id'          => 159155,
		'name'             => 'SD',
		'slug'             => 'cutemi-video-resolution-sd',
		'term_group'       => 0,
		'term_taxonomy_id' => 159042,
		'taxonomy'         => 'cutemi_video_resolution',
		'description'      => 'Standard Definiton',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '60',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
);
