<?php

$cutemi_taxonomies['cutemi_video_tech'] = array(
	0  => array(
		'term_id'          => 152309,
		'name'             => '3ivx',
		'slug'             => 'cutemi-video-tech-3ivx',
		'term_group'       => 0,
		'term_taxonomy_id' => 152196,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Codec suite created by 3ivx Technologies',
		'parent'           => 'cutemi-video-tech-mpeg-4-asp',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)3ivx,(?i)3IV2',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	1  => array(
		'term_id'          => 152306,
		'name'             => 'DivX',
		'slug'             => 'cutemi-video-tech-divx',
		'term_group'       => 0,
		'term_taxonomy_id' => 152193,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'DivX ( MPEG-4 ASP )',
		'parent'           => 'cutemi-video-tech-mpeg-4-asp',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)divx',
			'priority_sum'    => '6',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	2  => array(
		'term_id'          => 159249,
		'name'             => 'FLV1',
		'slug'             => 'cutemi-video-tech-flv1',
		'term_group'       => 0,
		'term_taxonomy_id' => 159136,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Sorenson Spark',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)FLV1,(?i)Sorenson Spark',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	3  => array(
		'term_id'          => 152301,
		'name'             => 'H.261',
		'slug'             => 'cutemi-video-tech-h261',
		'term_group'       => 0,
		'term_taxonomy_id' => 152188,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'H.261 (Px64)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)H(?: |-|\\.|)261, (?i)Px64',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	4  => array(
		'term_id'          => 152304,
		'name'             => 'H.263',
		'slug'             => 'cutemi-video-tech-h263',
		'term_group'       => 0,
		'term_taxonomy_id' => 152191,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'H.263',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)H(?: |-|\\.|)263',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	5  => array(
		'term_id'          => 152315,
		'name'             => 'H.265',
		'slug'             => 'cutemi-video-tech-h265',
		'term_group'       => 0,
		'term_taxonomy_id' => 152202,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'H.265 (HEVC)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)H(?: |-|\\.|)265, (?i)HEVC',
			'priority_sum'    => '4',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	6  => array(
		'term_id'          => 159252,
		'name'             => 'I263',
		'slug'             => 'cutemi-video-tech-i263',
		'term_group'       => 0,
		'term_taxonomy_id' => 159139,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Based on early drafts of the H.263',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)I263',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	7  => array(
		'term_id'          => 159269,
		'name'             => 'JPEG',
		'slug'             => 'cutemi-video-tech-jpeg',
		'term_group'       => 0,
		'term_taxonomy_id' => 159156,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'JPEG',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)JPEG',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	8  => array(
		'term_id'          => 159277,
		'name'             => 'MJPEG',
		'slug'             => 'cutemi-video-tech-mjpeg',
		'term_group'       => 0,
		'term_taxonomy_id' => 159164,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Motion JPEG',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)(Motion JPEG|ACDV|AVDJ|AVI1|AVI2|AVID|AVRn|CJPG|dmb1|IJLV|IJPG|jpeg|MJPG|mjpa|mjpb|MTSJ|MVJP|QIVG|SLMJ|ZJPG)',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	9  => array(
		'term_id'          => 152302,
		'name'             => 'MPEG-1',
		'slug'             => 'cutemi-video-tech-mpeg-1',
		'term_group'       => 0,
		'term_taxonomy_id' => 152189,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'MPEG-1 (Part 2)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)MPEG(?: |-|\\.|)1',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	10 => array(
		'term_id'          => 152303,
		'name'             => 'MPEG-2',
		'slug'             => 'cutemi-video-tech-mpeg-2',
		'term_group'       => 0,
		'term_taxonomy_id' => 152190,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'MPEG-2 (Part 2)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)MPEG(?: |-|\\.|)2',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	11 => array(
		'term_id'          => 159270,
		'name'             => 'MPEG-4',
		'slug'             => 'cutemi-video-tech-mpeg-4',
		'term_group'       => 0,
		'term_taxonomy_id' => 159157,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'MPEG-4 Part 2',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => 'MPEG-4 Visual,DCOD,DIGI,DXGM,FVFW',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	12 => array(
		'term_id'          => 152305,
		'name'             => 'MPEG-4 ASP',
		'slug'             => 'cutemi-video-tech-mpeg-4-asp',
		'term_group'       => 0,
		'term_taxonomy_id' => 152192,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'MPEG-4 Advanced Simple Profile',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)ASP',
			'priority_sum'    => '6',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	13 => array(
		'term_id'          => 152311,
		'name'             => 'MPEG-4 AVC',
		'slug'             => 'cutemi-video-tech-mpeg-4-avc',
		'term_group'       => 0,
		'term_taxonomy_id' => 152198,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'H.264, MPEG-4 Advanced Video Coding (MPEG-4 Part 10)',
		'parent'           => 0,
		'count'            => 2,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)H(?: |-|\\.|)264, (?i)AVC',
			'priority_sum'    => '7',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	14 => array(
		'term_id'          => 159248,
		'name'             => 'MPEG-4 SP',
		'slug'             => 'cutemi-video-tech-mpeg-4-sp',
		'term_group'       => 0,
		'term_taxonomy_id' => 159135,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'MPEG-4 Visual Simple Profile',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	15 => array(
		'term_id'          => 159257,
		'name'             => 'MPNG',
		'slug'             => 'cutemi-video-tech-mpng',
		'term_group'       => 0,
		'term_taxonomy_id' => 159144,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Motion PNG',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)MPNG,(?i)Motion PNG',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	16 => array(
		'term_id'          => 152333,
		'name'             => 'MVC',
		'slug'             => 'cutemi-video-tech-mvc',
		'term_group'       => 0,
		'term_taxonomy_id' => 152220,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Multiview Video Coding 3D',
		'parent'           => 'cutemi-video-tech-mpeg-4-avc',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)MVC,(?i)Multiview',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	17 => array(
		'term_id'          => 152308,
		'name'             => 'Nero Digital',
		'slug'             => 'cutemi-video-tech-mpeg-4-nero-digital',
		'term_group'       => 0,
		'term_taxonomy_id' => 152195,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Nero digital (MPEG-4 ASP)',
		'parent'           => 'cutemi-video-tech-mpeg-4-asp',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)nero(?: |-|\\.|)digital',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	18 => array(
		'term_id'          => 152313,
		'name'             => 'Nero Digital AVC',
		'slug'             => 'cutemi-video-tech-mpeg-4-nero-digital-avc',
		'term_group'       => 0,
		'term_taxonomy_id' => 152200,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Nero Digital for MPEG-4 AVC',
		'parent'           => 'cutemi-video-tech-mpeg-4-avc',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => 'Nero(?: |-|\\.|)Digital(?: |-|\\.|)AVC',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	19 => array(
		'term_id'          => 159247,
		'name'             => 'Old WMV',
		'slug'             => 'cutemi-video-tech-wmv-old',
		'term_group'       => 0,
		'term_taxonomy_id' => 159134,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Microsoft MPEG-4 version X',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)(MPG4|MP42|MP43|MP4S|M4S2)',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	20 => array(
		'term_id'          => 152310,
		'name'             => 'Quicktime 6',
		'slug'             => 'cutemi-video-tech-quicktime-6',
		'term_group'       => 0,
		'term_taxonomy_id' => 152197,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Quicktime 6',
		'parent'           => 'cutemi-video-tech-mpeg-4-asp',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)qt6',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	21 => array(
		'term_id'          => 159268,
		'name'             => 'Quicktime 6 (SP)',
		'slug'             => 'cutemi-video-tech-quicktime-6-sp',
		'term_group'       => 0,
		'term_taxonomy_id' => 159155,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Quicktime 6 (Simple Profile)',
		'parent'           => 'cutemi-video-tech-mpeg-4-sp',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	22 => array(
		'term_id'          => 152314,
		'name'             => 'QuickTime 7',
		'slug'             => 'cutemi-video-tech-quicktime-7',
		'term_group'       => 0,
		'term_taxonomy_id' => 152201,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Quicktime 7',
		'parent'           => 'cutemi-video-tech-mpeg-4-avc',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)qt7, (?i)quicktime(?: |-|\\.|)7',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	23 => array(
		'term_id'          => 152327,
		'name'             => 'RealVideo 1',
		'slug'             => 'cutemi-video-tech-r10-r13',
		'term_group'       => 0,
		'term_taxonomy_id' => 152214,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'RV10 or RV13: RealVideo 1',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)RV10,(?i)RealVideo(?: |-|\\.|)1',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	24 => array(
		'term_id'          => 152331,
		'name'             => 'RealVideo 11',
		'slug'             => 'cutemi-video-tech-rv60',
		'term_group'       => 0,
		'term_taxonomy_id' => 152218,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'RV60:  RealVideo 11 (RealMedia HD)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)RV60,(?i)RV11,RealVideo(?: |-|\\.|)11,RealMedia(?: |-|\\.|)HD',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	25 => array(
		'term_id'          => 152329,
		'name'             => 'RealVideo 8',
		'slug'             => 'cutemi-video-tech-rv30',
		'term_group'       => 0,
		'term_taxonomy_id' => 152216,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'RV30:  RealVideo 8',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)RV30,(?i)RealVideo(?: |-|\\.|)8',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	26 => array(
		'term_id'          => 152330,
		'name'             => 'RealVideo 9',
		'slug'             => 'cutemi-video-tech-rv40',
		'term_group'       => 0,
		'term_taxonomy_id' => 152217,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'RV40  RealVideo 9/10 (aka RV9)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)RV40,(?i)RV9,RealVideo(?: |-|\\.|)9,RealVideo(?: |-|\\.|)10',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	27 => array(
		'term_id'          => 152328,
		'name'             => 'RealVideo G2',
		'slug'             => 'cutemi-video-tech-rv20',
		'term_group'       => 0,
		'term_taxonomy_id' => 152215,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'RV20:  RealVideo G2 and RealVideo G2+SVT,',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)RV20,(?i)RealVideo(?: |-|\\.|)G2',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	28 => array(
		'term_id'          => 159250,
		'name'             => 'SVQ1',
		'slug'             => 'cutemi-video-tech-svq1',
		'term_group'       => 0,
		'term_taxonomy_id' => 159137,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Sorenson Video',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)Sorenson Video,(?i)SVQ1',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	29 => array(
		'term_id'          => 159251,
		'name'             => 'SVQ3',
		'slug'             => 'cutemi-video-tech-svq3',
		'term_group'       => 0,
		'term_taxonomy_id' => 159138,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Sorenson Video 3',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)Sorenson Video 3,(?i)SVQ3',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	30 => array(
		'term_id'          => 152332,
		'name'             => 'Theora',
		'slug'             => 'cutemi-video-tech-theora',
		'term_group'       => 0,
		'term_taxonomy_id' => 152219,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Theora',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)theora',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	31 => array(
		'term_id'          => 152316,
		'name'             => 'VC-1',
		'slug'             => 'cutemi-video-tech-vc-1',
		'term_group'       => 0,
		'term_taxonomy_id' => 152203,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'SMPTE 421M',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)VC(?: |-|\\.|)1',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	32 => array(
		'term_id'          => 152320,
		'name'             => 'VP3',
		'slug'             => 'cutemi-video-tech-vp3',
		'term_group'       => 0,
		'term_taxonomy_id' => 152207,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'VP3 video codec (On2 Technologies)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)VP3',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	33 => array(
		'term_id'          => 152321,
		'name'             => 'VP4',
		'slug'             => 'cutemi-video-tech-vp4',
		'term_group'       => 0,
		'term_taxonomy_id' => 152208,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'VP4 video codec (On2 Technologies)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)VP4',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	34 => array(
		'term_id'          => 152322,
		'name'             => 'VP5',
		'slug'             => 'cutemi-video-tech-vp5',
		'term_group'       => 0,
		'term_taxonomy_id' => 152209,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'VP5 video codec (On2 Technologies)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)VP5',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	35 => array(
		'term_id'          => 152323,
		'name'             => 'VP6',
		'slug'             => 'cutemi-video-tech-vp6',
		'term_group'       => 0,
		'term_taxonomy_id' => 152210,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'VP6 video codec (On2 Technologies)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)VP6',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	36 => array(
		'term_id'          => 152324,
		'name'             => 'VP7',
		'slug'             => 'cutemi-video-tech-vp7',
		'term_group'       => 0,
		'term_taxonomy_id' => 152211,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'VP7 video codec (On2 Technologies)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)VP7',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	37 => array(
		'term_id'          => 152325,
		'name'             => 'VP8',
		'slug'             => 'cutemi-video-tech-vp8',
		'term_group'       => 0,
		'term_taxonomy_id' => 152212,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'VP8 video codec (On2 Technologies)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)VP8',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	38 => array(
		'term_id'          => 152326,
		'name'             => 'VP9',
		'slug'             => 'cutemi-video-tech-vp9',
		'term_group'       => 0,
		'term_taxonomy_id' => 152213,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'VP9 video codec ',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)VP9',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	39 => array(
		'term_id'          => 159272,
		'name'             => 'WebP',
		'slug'             => 'cutemi-video-tech-webp',
		'term_group'       => 0,
		'term_taxonomy_id' => 159159,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'WebP Image format',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	40 => array(
		'term_id'          => 159246,
		'name'             => 'WMV1',
		'slug'             => 'cutemi-video-tech-wmv1',
		'term_group'       => 0,
		'term_taxonomy_id' => 159133,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Vídeo de Windows Media 7',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)wmv1',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	41 => array(
		'term_id'          => 159245,
		'name'             => 'WMV2',
		'slug'             => 'cutemi-video-tech-wmv2',
		'term_group'       => 0,
		'term_taxonomy_id' => 159132,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Vídeo de Windows Media 8',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)wmv2',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	42 => array(
		'term_id'          => 152317,
		'name'             => 'WMV3',
		'slug'             => 'cutemi-video-tech-wmv3',
		'term_group'       => 0,
		'term_taxonomy_id' => 152204,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Windows Media Video 9',
		'parent'           => 'cutemi-video-tech-vc-1',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)wmv3',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	43 => array(
		'term_id'          => 152318,
		'name'             => 'WMVA',
		'slug'             => 'cutemi-video-tech-wmva',
		'term_group'       => 0,
		'term_taxonomy_id' => 152205,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Windows Media Video 9 Advanced Profile (WMVA)',
		'parent'           => 'cutemi-video-tech-vc-1',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)wmva',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	44 => array(
		'term_id'          => 152319,
		'name'             => 'WVC1',
		'slug'             => 'cutemi-video-tech-wvc1',
		'term_group'       => 0,
		'term_taxonomy_id' => 152206,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Windows Media Video 9 Advanced Profile',
		'parent'           => 'cutemi-video-tech-vc-1',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)wvc1',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	45 => array(
		'term_id'          => 152312,
		'name'             => 'x264',
		'slug'             => 'cutemi-video-tech-x264',
		'term_group'       => 0,
		'term_taxonomy_id' => 152199,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'x264 encoding video streams into the H.264 format',
		'parent'           => 'cutemi-video-tech-mpeg-4-avc',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)x264',
			'priority_sum'    => '7',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	46 => array(
		'term_id'          => 152307,
		'name'             => 'Xvid',
		'slug'             => 'cutemi-video-tech-xvid',
		'term_group'       => 0,
		'term_taxonomy_id' => 152194,
		'taxonomy'         => 'cutemi_video_tech',
		'description'      => 'Xvid ( MPEG-4 ASP )',
		'parent'           => 'cutemi-video-tech-mpeg-4-asp',
		'count'            => 2,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)Xvid',
			'priority_sum'    => '5',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
);
