<?php

$cutemi_taxonomies['cutemi_site_source'] = array(
	0  => array(
		'term_id'          => 159158,
		'name'             => '1fichier',
		'slug'             => 'cutemi-link-source-1fichier',
		'term_group'       => 0,
		'term_taxonomy_id' => 159045,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\.)?(?:1fichier\\.com|alterupload\\.com|cjoint\\.net|desfichiers\\.net|dfichiers\\.com|megadl\\.fr|mesfichiers\\.org|piecejointe\\.net|pjointe\\.com|tenvoi\\.com|dl4free\\.com)/\\?([a-z0-9]{5,20})',
			'url_template'       => 'https://1fichier.com/?%ID%',
			'url_template_title' => 'https://1fichier.com/check_links.pl?links[]=https://1fichier.com/?%ID%',
			'url_template_size'  => 'https://1fichier.com/check_links.pl?links[]=https://1fichier.com/?%ID%',
			'regex_title'        => '[^;]*;([^;]+);\\d+',
			'regex_size'         => '[^;]*;[^;]+;(\\d+)',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	1  => array(
		'term_id'          => 159160,
		'name'             => 'Amazon',
		'slug'             => 'cutemi-link-source-amazon-drive',
		'term_group'       => 0,
		'term_taxonomy_id' => 159047,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\.)?amazon\\.(?:ca|com)/(?:gp/|cloud)drive/share(?:/|\\?s=)([A-Za-z0-9_-]+)',
			'url_template'       => 'https://www.amazon.ca/clouddrive/share/%ID%',
			'url_template_title' => 'https://www.amazon.com/drive/v1/shares/%ID%?shareId=%ID%&resourceVersion=V2&ContentType=JSON&_=%TIME%',
			'url_template_size'  => 'https://www.amazon.com/drive/v1/shares/%ID%?shareId=%ID%&resourceVersion=V2&ContentType=JSON&_=%TIME%',
			'regex_title'        => '"nodeInfo".*?"name":"([^"]*)"',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	2  => array(
		'term_id'          => 159159,
		'name'             => 'Amazon UE',
		'slug'             => 'cutemi-link-source-amazon-drive-ue',
		'term_group'       => 0,
		'term_taxonomy_id' => 159046,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\.)?amazon\\.(?:de|es|co\\.uk|fr|it)/(?:gp/|cloud)drive/share(?:/|\\?s=)([A-Za-z0-9_-]+)',
			'url_template'       => 'https://www.amazon.es/clouddrive/share/%ID%',
			'url_template_title' => 'https://www.amazon.es/drive/v1/shares/%ID%?shareId=%ID%&resourceVersion=V2&ContentType=JSON&_=%TIME%',
			'url_template_size'  => 'https://www.amazon.es/drive/v1/shares/%ID%?shareId=%ID%&resourceVersion=V2&ContentType=JSON&_=%TIME%',
			'regex_title'        => '"nodeInfo".*?"name":"([^"]*)"',
			'regex_size'         => '',
			'hidden'             => '1',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '0',
		),
	),
	3  => array(
		'term_id'          => 159161,
		'name'             => 'box',
		'slug'             => 'cutemi-link-source-box',
		'term_group'       => 0,
		'term_taxonomy_id' => 159048,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:\\w+\\.)*box\\.(?:com|net)/s(?:hared)?/([a-z0-9]{32}|[a-z0-9]{20})(?:$|[^a-z0-9])',
			'url_template'       => 'https://app.box.com/s/%ID%',
			'url_template_title' => 'https://app.box.com/s/%ID%',
			'url_template_size'  => 'https://app.box.com/s/%ID%',
			'regex_title'        => '"type":"file".*?"name":"([^"]*)","itemSize":',
			'regex_size'         => '"type":"file".*?"name":"[^"]*","itemSize":([0-9]*)',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	4  => array(
		'term_id'          => 159162,
		'name'             => 'Clicknupload',
		'slug'             => 'cutemi-link-source-clicknupload',
		'term_group'       => 0,
		'term_taxonomy_id' => 159049,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\\\.)?(?:clicknupload.cc|clicknupload.co|clicknupload.org|clicknupload.com|clicknupload.me|clicknupload.link)/(?:d/|embed-|)([A-Za-z0-9]*)(?:/([^/]+)(?:\\.html)?|$)',
			'url_template'       => 'https://clicknupload.cc/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	5  => array(
		'term_id'          => 159163,
		'name'             => 'DailyUploads',
		'slug'             => 'cutemi-link-source-dailyuploads',
		'term_group'       => 0,
		'term_taxonomy_id' => 159050,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\\\.)?(?:dailyuploads\\.net|dailyuploads\\.cc)/(?:d/|embed-|)([A-Za-z0-9]*)(?:/([^/]+)(?:\\.html)?|$)',
			'url_template'       => 'https://dailyuploads.net/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	6  => array(
		'term_id'          => 159164,
		'name'             => 'ddownload',
		'slug'             => 'cutemi-link-source-ddownload',
		'term_group'       => 0,
		'term_taxonomy_id' => 159051,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\\\.)?(?:ddownload.com|ddl.to|api.ddl.to|esimpurcuesc.ddownload.com)/(?:d/|embed-|)([A-Za-z0-9]*)(?:/([^/]+)(?:\\.html)?|$)',
			'url_template'       => 'https://ddownload.com/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	7  => array(
		'term_id'          => 159166,
		'name'             => 'Dropapk',
		'slug'             => 'cutemi-link-source-dropapk',
		'term_group'       => 0,
		'term_taxonomy_id' => 159053,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\\\.)?(?:drop.download|dropapk.to|dropapk.com)/(?:d/|embed-|)([A-Za-z0-9]*)(?:/([^/]+)(?:\\.html)?|$)',
			'url_template'       => 'https://drop.download/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	8  => array(
		'term_id'          => 159167,
		'name'             => 'Dropbox',
		'slug'             => 'cutemi-link-source-dropbox',
		'term_group'       => 0,
		'term_taxonomy_id' => 159054,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\.)?dropbox\\.com/((?:sh|s|sc)/.+)',
			'url_template'       => 'https://www.dropbox.com/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '"bytes":\\s*[0-9]*[^{}]*\\"filename\\":\\s*\\"([^"]*)\\"',
			'regex_size'         => '"bytes":\\s*([0-9]*)[^{}]*\\"filename\\":\\s*\\"[^"]*\\"',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	9  => array(
		'term_id'          => 159165,
		'name'             => 'Fast Down',
		'slug'             => 'cutemi-link-source-fastdown',
		'term_group'       => 0,
		'term_taxonomy_id' => 159052,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\\\.)?(?:down.fast-down.com)/(?:d/|embed-|)([A-Za-z0-9]*)(?:/([^/]+)(?:\\.html)?|$)',
			'url_template'       => 'https://down.fast-down.com/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	10 => array(
		'term_id'          => 159168,
		'name'             => 'FastClick',
		'slug'             => 'cutemi-link-source-fastclick',
		'term_group'       => 0,
		'term_taxonomy_id' => 159055,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\\\.)?(?:fastclick\\.to)/(?:d/|embed-|)([A-Za-z0-9]*)(?:/([^/]+)(?:\\.html)?|$)',
			'url_template'       => 'https://fastclick.to/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	11 => array(
		'term_id'          => 159169,
		'name'             => 'FileFactory',
		'slug'             => 'cutemi-link-source-filefactory',
		'term_group'       => 0,
		'term_taxonomy_id' => 159056,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\.)?filefactory\\.com/file/([^/]+)/?(.*)',
			'url_template'       => 'https://www.filefactory.com/file/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => 'class="file-name[^>]*>([^<]*)<',
			'regex_size'         => 'id="file_info"[^>]*>\\s*([\\d\\.]+ (?:KB|MB|GB|TB))',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	12 => array(
		'term_id'          => 159170,
		'name'             => 'GDrive',
		'slug'             => 'cutemi-link-source-gdrive',
		'term_group'       => 0,
		'term_taxonomy_id' => 159057,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:drive.google.com|docs.google.com)/file/d/([a-zA-Z0-9\\-_]+)
https?://(?:drive.google.com|docs.google.com)/(?:leaf|open)\\?([^<>"/]+)?id=([A-Za-z0-9\\-_]+)
https?://(?:drive.google.com|docs.google.com)/(?:u/\\d+/)?uc\\?id=([A-Za-z0-9\\-_]+)',
			'url_template'       => 'https://drive.google.com/file/d/%ID%/view',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => 'property="og:title"\\s+content="([^"]*)"',
			'regex_size'         => 'itemJson:\\s*\\[.*?download[^\\[]*\\[[^,]*,[^,]*,"([0-9]*)"\\]',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	13 => array(
		'term_id'          => 159171,
		'name'             => 'HexUpload',
		'slug'             => 'cutemi-link-source-hexupload',
		'term_group'       => 0,
		'term_taxonomy_id' => 159058,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\\\.)?(?:hexupload.net|hexupload.com)/(?:d/|embed-|)([A-Za-z0-9]*)(?:/([^/]+)(?:\\.html)?|$)',
			'url_template'       => 'https://hexupload.net/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	14 => array(
		'term_id'          => 159172,
		'name'             => 'Jottacloud',
		'slug'             => 'cutemi-link-source-jottacloud',
		'term_group'       => 0,
		'term_taxonomy_id' => 159059,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\.)?jottacloud.com/s/([a-f0-9]*)',
			'url_template'       => 'https://www.jottacloud.com/s/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '\\sdata-open=\'{"name":"([^"]*)"',
			'regex_size'         => '\\sdata-open=\'{"name":"[^}]*?"size":"([0-9\\.,]*\\s*(?:B|KB|MB|GB|TB))',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	15 => array(
		'term_id'          => 159173,
		'name'             => 'KatFile',
		'slug'             => 'cutemi-link-source-katfile',
		'term_group'       => 0,
		'term_taxonomy_id' => 159060,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\\\.)?(?:katfile.com)/(?:d/|embed-|)([A-Za-z0-9]*)(?:/([^/]+)(?:\\.html)?|$)',
			'url_template'       => 'https://katfile.com/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	16 => array(
		'term_id'          => 159174,
		'name'             => 'Mediafire',
		'slug'             => 'cutemi-link-source-mediafire',
		'term_group'       => 0,
		'term_taxonomy_id' => 159061,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\.|m\\.)?mediafire\\.com/(?:download/|download\\.php\\?|file/|file\\.php\\?|file\\?|\\?)([a-z0-9]+)',
			'url_template'       => 'https://www.mediafire.com/file/%ID%',
			'url_template_title' => 'https://www.mediafire.com/api/1.5/file/get_info.php?r=%TIME%&quick_key=%ID%&response_format=json',
			'url_template_size'  => 'https://www.mediafire.com/api/1.5/file/get_info.php?r=%TIME%&quick_key=%ID%&response_format=json',
			'regex_title'        => '"filename":"([^"]*)',
			'regex_size'         => '"size":"([^"]*)',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	17 => array(
		'term_id'          => 159175,
		'name'             => 'MEGA',
		'slug'             => 'cutemi-link-source-mega',
		'term_group'       => 0,
		'term_taxonomy_id' => 159062,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\.)?mega\\.(?:co\\.)?nz/(?:embed/|file/|#!)((?:[a-zA-Z0-9\\-_]+)#(?:[a-zA-Z0-9\\-_]+))',
			'url_template'       => 'https://mega.nz/file/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	18 => array(
		'term_id'          => 159176,
		'name'             => 'MEGA Folder',
		'slug'             => 'cutemi-link-source-mega-folder',
		'term_group'       => 0,
		'term_taxonomy_id' => 159063,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\.)?mega\\.(?:co\\.)?nz/(?:folder/|#F!)((?:[a-z0-9\\-_]+)[!#](?:[a-z0-9\\-_]+)(?:/file/[a-z0-9\\-_]+)?)',
			'url_template'       => 'https://mega.nz/folder/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	19 => array(
		'term_id'          => 159177,
		'name'             => 'NitroFlare',
		'slug'             => 'cutemi-link-source-nitroflare',
		'term_group'       => 0,
		'term_taxonomy_id' => 159064,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\.)?(?:nitroflare\\.(?:com|net)|nitro\\.download)/(?:view|watch)/([A-Z0-9]+)',
			'url_template'       => 'https://nitro.download/view/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => 'alt="" /><span title="([^<>"]*?)">',
			'regex_size'         => 'dir="ltr" style="text-align: left;">\\s*([0-9\\.,]*\\s*(?:B|KB|MB|GB|TB))\\s*</span>',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	20 => array(
		'term_id'          => 159178,
		'name'             => 'OneDrive',
		'slug'             => 'cutemi-link-source-onedrive',
		'term_group'       => 0,
		'term_taxonomy_id' => 159065,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\.)?onedrive\\.live\\.com/((?:redir|view\\.aspx)?\\?[A-Za-z0-9\\&\\!=#\\%.,]+)',
			'url_template'       => 'https://www.onedrive.live.com/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	21 => array(
		'term_id'          => 159179,
		'name'             => 'pCloud',
		'slug'             => 'cutemi-link-source-pcloud',
		'term_group'       => 0,
		'term_taxonomy_id' => 159066,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:(?:[a-z0-9]*[^e]\\.pcloud\\.(?:com|link))/(?:#page=publink\\&|publink/show\\?)code=|pc\\.cd/)([A-Za-z0-9]+)',
			'url_template'       => 'https://u.pcloud.link/publink/show?code=%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	22 => array(
		'term_id'          => 159180,
		'name'             => 'pCloud(Euro)',
		'slug'             => 'cutemi-link-source-pcloud-e',
		'term_group'       => 0,
		'term_taxonomy_id' => 159067,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:(?:[a-z0-9]*e\\.pcloud\\.(?:com|link))/(?:#page=publink\\&|publink/show\\?)code=|pc\\.cd/)([A-Za-z0-9]+)',
			'url_template'       => 'https://u.pcloud.link/publink/show?code=%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	23 => array(
		'term_id'          => 159181,
		'name'             => 'Rapidgator',
		'slug'             => 'cutemi-link-source-rapidgator',
		'term_group'       => 0,
		'term_taxonomy_id' => 159068,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\.)?(?:rapidgator\\.net|rapidgator\\.asia|rg\\.to)/file/([a-z0-9]{32}|\\d+)(?:/([^/<>]+)\\.html)?',
			'url_template'       => 'https://rapidgator.net/file/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => 'Downloading\\s*:\\s*</strong>\\s*<a href=""[^>]*>\\s*([^<>"]+?)\\s*<',
			'regex_size'         => 'File size:\\s*<strong>([^<>"]+)</strong>',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	24 => array(
		'term_id'          => 151976,
		'name'             => 'Uploaded',
		'slug'             => 'cutemi-link-source-uploaded',
		'term_group'       => 0,
		'term_taxonomy_id' => 151863,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 2,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => '^https?://(?:www\\.)?(?:uploaded\\.to|uploaded\\.net|ul\\.to)/(?:file/|\\?id=|)([a-zA-Z0-9_\\-]*)',
			'url_template'       => 'https://uploaded.net/file/%ID%/%TITLE%',
			'url_template_title' => 'http://uploaded.net/file/%ID%/status',
			'url_template_size'  => 'http://uploaded.net/file/%ID%/status',
			'regex_title'        => '^([^\\n\\r]*)[\\r\\n]([0-9\\, TGBMK]+)$',
			'regex_size'         => '^[^\\n\\r]*[\\r\\n]([0-9\\, TGBMK]+)$',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	25 => array(
		'term_id'          => 159182,
		'name'             => 'UploadGIG',
		'slug'             => 'cutemi-link-source-uploadgig',
		'term_group'       => 0,
		'term_taxonomy_id' => 159069,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\.)?uploadgig\\.com/file/download/([A-Za-z0-9]+)(?:/([A-Za-z0-9%\\.\\-_]+))?',
			'url_template'       => 'https://uploadgig.com/file/download/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => 'class="filename">([^<>"]+)<',
			'regex_size'         => 'class="filesize">\\[([^<>"]+)\\]<',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	26 => array(
		'term_id'          => 151975,
		'name'             => 'Uptobox',
		'slug'             => 'cutemi-link-source-uptobox',
		'term_group'       => 0,
		'term_taxonomy_id' => 151862,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 4,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => '^https?://uptobox.com/([a-zA-Z0-9_-]+)',
			'url_template'       => 'https://uptobox.com/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => 'class=\'file-title\'>([^<>"]+) \\(\\d+[^\\)]+\\)\\s*<',
			'regex_size'         => 'class=\'file-title\'>[^<>"]+ \\(([0-9.]+\\s*(?(?=[KMGT])(?:[KMGT])(?:i?B)?|B))\\)\\s*<',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	27 => array(
		'term_id'          => 159183,
		'name'             => 'Usersdrive',
		'slug'             => 'cutemi-link-source-usersdrive',
		'term_group'       => 0,
		'term_taxonomy_id' => 159070,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => 'https?://(?:www\\\\.)?(?:usersdrive.com)/(?:d/|embed-|)([A-Za-z0-9]*)(?:\\.html)?(?:/([^/]+)(?:\\.html)?|$)',
			'url_template'       => 'https://usersdrive.com/%ID%',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '50',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
	28 => array(
		'term_id'          => 189162,
		'name'             => 'Generic',
		'slug'             => 'cutemi-link-source-generic',
		'term_group'       => 0,
		'term_taxonomy_id' => 189172,
		'taxonomy'         => 'cutemi_site_source',
		'description'      => '',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'extract_regexs'     => '',
			'url_template'       => '',
			'url_template_title' => '',
			'url_template_size'  => '',
			'regex_title'        => '',
			'regex_size'         => '',
			'hidden'             => '',
			'priority_sum'       => '90',
			'image_url'          => '',
			'cutemi_disabled'    => '',
		),
	),
);
