<?php

$cutemi_taxonomies['cutemi_video_bitrate'] = array(
	0  => array(
		'term_id'          => 159330,
		'name'             => '1 Mbps',
		'slug'             => 'cutemi-video-bitrate-1-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159217,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 1 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '190',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	1  => array(
		'term_id'          => 159331,
		'name'             => '1.5 Mbps',
		'slug'             => 'cutemi-video-bitrate-1-5-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159218,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 1.5 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '185',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	2  => array(
		'term_id'          => 159343,
		'name'             => '10 Mbps',
		'slug'             => 'cutemi-video-bitrate-10-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159230,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 10 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '125',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	3  => array(
		'term_id'          => 159359,
		'name'             => '100 Mbps',
		'slug'             => 'cutemi-video-bitrate-100-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159246,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 100 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '45',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	4  => array(
		'term_id'          => 159360,
		'name'             => '110 Mbps',
		'slug'             => 'cutemi-video-bitrate-110-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159247,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 110 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '40',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	5  => array(
		'term_id'          => 159344,
		'name'             => '12 Mbps',
		'slug'             => 'cutemi-video-bitrate-12-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159231,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 12 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '120',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	6  => array(
		'term_id'          => 159361,
		'name'             => '120 Mbps',
		'slug'             => 'cutemi-video-bitrate-120-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159248,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 120 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '35',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	7  => array(
		'term_id'          => 159362,
		'name'             => '130 Mbps',
		'slug'             => 'cutemi-video-bitrate-130-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159249,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 130 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '30',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	8  => array(
		'term_id'          => 159345,
		'name'             => '14 Mbps',
		'slug'             => 'cutemi-video-bitrate-14-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159232,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 14 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '115',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	9  => array(
		'term_id'          => 159363,
		'name'             => '140 Mbps',
		'slug'             => 'cutemi-video-bitrate-140-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159250,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 140 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '25',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	10 => array(
		'term_id'          => 159364,
		'name'             => '150 Mbps',
		'slug'             => 'cutemi-video-bitrate-150-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159251,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 150 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '20',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	11 => array(
		'term_id'          => 159346,
		'name'             => '16 Mbps',
		'slug'             => 'cutemi-video-bitrate-16-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159233,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 16 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '110',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	12 => array(
		'term_id'          => 159365,
		'name'             => '175 Mbps',
		'slug'             => 'cutemi-video-bitrate-175-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159252,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 175 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '15',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	13 => array(
		'term_id'          => 159347,
		'name'             => '18 Mbps',
		'slug'             => 'cutemi-video-bitrate-18-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159234,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 18 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '105',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	14 => array(
		'term_id'          => 159332,
		'name'             => '2 Mbps',
		'slug'             => 'cutemi-video-bitrate-2-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159219,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 2 Mbps',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '180',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	15 => array(
		'term_id'          => 159333,
		'name'             => '2.5 Mbps',
		'slug'             => 'cutemi-video-bitrate-2-5-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159220,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 2.5 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '175',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	16 => array(
		'term_id'          => 159348,
		'name'             => '20 Mbps',
		'slug'             => 'cutemi-video-bitrate-20-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159235,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 20 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '100',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	17 => array(
		'term_id'          => 159366,
		'name'             => '200 Mbps',
		'slug'             => 'cutemi-video-bitrate-200-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159253,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 200 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '10',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	18 => array(
		'term_id'          => 159349,
		'name'             => '25 Mbps',
		'slug'             => 'cutemi-video-bitrate-25-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159236,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 25 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '95',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	19 => array(
		'term_id'          => 159328,
		'name'             => '250 kbps',
		'slug'             => 'cutemi-video-bitrate-250-k',
		'term_group'       => 0,
		'term_taxonomy_id' => 159215,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 250 kbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '200',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	20 => array(
		'term_id'          => 159334,
		'name'             => '3 Mbps',
		'slug'             => 'cutemi-video-bitrate-3-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159221,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 3 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '170',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	21 => array(
		'term_id'          => 159335,
		'name'             => '3.5 Mbps',
		'slug'             => 'cutemi-video-bitrate-3-5-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159222,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 3.5 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '165',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	22 => array(
		'term_id'          => 159350,
		'name'             => '30 Mbps',
		'slug'             => 'cutemi-video-bitrate-30-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159237,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 30 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '90',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	23 => array(
		'term_id'          => 159351,
		'name'             => '35 Mbps',
		'slug'             => 'cutemi-video-bitrate-35-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159238,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 35 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '85',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	24 => array(
		'term_id'          => 159336,
		'name'             => '4 Mbps',
		'slug'             => 'cutemi-video-bitrate-4-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159223,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 4 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '160',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	25 => array(
		'term_id'          => 159337,
		'name'             => '4.5 Mbps',
		'slug'             => 'cutemi-video-bitrate-4-5-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159224,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 4.5 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '155',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	26 => array(
		'term_id'          => 159352,
		'name'             => '40 Mbps',
		'slug'             => 'cutemi-video-bitrate-40-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159239,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 40 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '80',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	27 => array(
		'term_id'          => 159353,
		'name'             => '45 Mbps',
		'slug'             => 'cutemi-video-bitrate-45-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159240,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 45 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '75',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	28 => array(
		'term_id'          => 159338,
		'name'             => '5 Mbps',
		'slug'             => 'cutemi-video-bitrate-5-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159225,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 5 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '150',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	29 => array(
		'term_id'          => 159354,
		'name'             => '50 Mbps',
		'slug'             => 'cutemi-video-bitrate-50-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159241,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 50 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '70',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	30 => array(
		'term_id'          => 159329,
		'name'             => '500 kbps',
		'slug'             => 'cutemi-video-bitrate-500-k',
		'term_group'       => 0,
		'term_taxonomy_id' => 159216,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 500 kbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '195',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	31 => array(
		'term_id'          => 159339,
		'name'             => '6 Mbps',
		'slug'             => 'cutemi-video-bitrate-6-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159226,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 6 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '145',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	32 => array(
		'term_id'          => 159355,
		'name'             => '60 Mbps',
		'slug'             => 'cutemi-video-bitrate-60-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159242,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 60 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '65',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	33 => array(
		'term_id'          => 159340,
		'name'             => '7 Mbps',
		'slug'             => 'cutemi-video-bitrate-7-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159227,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 7 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '140',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	34 => array(
		'term_id'          => 159356,
		'name'             => '70 Mbps',
		'slug'             => 'cutemi-video-bitrate-70-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159243,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 70 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '60',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	35 => array(
		'term_id'          => 159341,
		'name'             => '8 Mbps',
		'slug'             => 'cutemi-video-bitrate-8-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159228,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 8 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '135',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	36 => array(
		'term_id'          => 159357,
		'name'             => '80 Mbps',
		'slug'             => 'cutemi-video-bitrate-80-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159244,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 80 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '55',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	37 => array(
		'term_id'          => 159342,
		'name'             => '9 Mbps',
		'slug'             => 'cutemi-video-bitrate-9-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159229,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 9 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '130',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	38 => array(
		'term_id'          => 159358,
		'name'             => '90 Mbps',
		'slug'             => 'cutemi-video-bitrate-90-m',
		'term_group'       => 0,
		'term_taxonomy_id' => 159245,
		'taxonomy'         => 'cutemi_video_bitrate',
		'description'      => 'Approximately 90 Mbps',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '50',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
);
