<?php

$cutemi_taxonomies['cutemi_text_format'] = array(
	0  => array(
		'term_id'          => 152348,
		'name'             => 'ASS',
		'slug'             => 'cutemi-text-format-ass',
		'term_group'       => 0,
		'term_taxonomy_id' => 152235,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'ASS (Advanced SSA) subtitle',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	1  => array(
		'term_id'          => 159229,
		'name'             => 'BMP',
		'slug'             => 'cutemi-text-format-bmp',
		'term_group'       => 0,
		'term_taxonomy_id' => 159116,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'Basic image based subtitle format',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	2  => array(
		'term_id'          => 159239,
		'name'             => 'CFF-T',
		'slug'             => 'cutemi-text-format-cff-t',
		'term_group'       => 0,
		'term_taxonomy_id' => 159126,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'Common File Format Timed Text',
		'parent'           => 'cutemi-text-format-ttml',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	3  => array(
		'term_id'          => 159276,
		'name'             => 'CMML',
		'slug'             => 'cutemi-text-format-cmml',
		'term_group'       => 0,
		'term_taxonomy_id' => 159163,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'Continuous Media Markup Language',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)CMML,(?i)Continuous Media Markup Language',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	4  => array(
		'term_id'          => 159275,
		'name'             => 'CVD',
		'slug'             => 'cutemi-text-format-cvd',
		'term_group'       => 0,
		'term_taxonomy_id' => 159162,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'China Video Discs Subtitles',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)China Video Discs Subtitles,(?i)CVD',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	5  => array(
		'term_id'          => 159254,
		'name'             => 'DivX',
		'slug'             => 'cutemi-text-format-divx',
		'term_group'       => 0,
		'term_taxonomy_id' => 159141,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'DivX Subtitle',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)DXSB',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	6  => array(
		'term_id'          => 152349,
		'name'             => 'DVB',
		'slug'             => 'cutemi-text-format-dvb-subtitle',
		'term_group'       => 0,
		'term_taxonomy_id' => 152236,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'DVB subtitles',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	7  => array(
		'term_id'          => 152350,
		'name'             => 'DVB teletext',
		'slug'             => 'cutemi-text-format-dvb-teletext',
		'term_group'       => 0,
		'term_taxonomy_id' => 152237,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'DVB teletext',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	8  => array(
		'term_id'          => 152351,
		'name'             => 'DVD subtitles',
		'slug'             => 'cutemi-text-format-dvd-subtitle',
		'term_group'       => 0,
		'term_taxonomy_id' => 152238,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'DVD subtitles',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	9  => array(
		'term_id'          => 159234,
		'name'             => 'EBU-STL',
		'slug'             => 'cutemi-text-format-ebu-stl',
		'term_group'       => 0,
		'term_taxonomy_id' => 159121,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'EBU Subtitles/Teletext (EBU 3264)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	10 => array(
		'term_id'          => 159236,
		'name'             => 'EBU-TT',
		'slug'             => 'cutemi-text-format-ebu-tt',
		'term_group'       => 0,
		'term_taxonomy_id' => 159123,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'EBU Timed Text (EBU Tech 3350)',
		'parent'           => 'cutemi-text-format-ttml',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	11 => array(
		'term_id'          => 159237,
		'name'             => 'EBU-TT-D',
		'slug'             => 'cutemi-text-format-ebu-tt-d',
		'term_group'       => 0,
		'term_taxonomy_id' => 159124,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => ' EBU Tech 3380',
		'parent'           => 'cutemi-text-format-ttml',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	12 => array(
		'term_id'          => 152352,
		'name'             => 'EIA-608',
		'slug'             => 'cutemi-text-format-eia-608-cc',
		'term_group'       => 0,
		'term_taxonomy_id' => 152239,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'EIA-608 closed captions',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	13 => array(
		'term_id'          => 159231,
		'name'             => 'EIA-708',
		'slug'             => 'cutemi-text-format-eia-708-cc',
		'term_group'       => 0,
		'term_taxonomy_id' => 159118,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'EIA-708 closed captions',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	14 => array(
		'term_id'          => 152353,
		'name'             => 'HDMV PSG',
		'slug'             => 'cutemi-text-format-hdmv-pgs',
		'term_group'       => 0,
		'term_taxonomy_id' => 152240,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'HDMV Presentation Graphic Stream subtitles',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)PGS',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	15 => array(
		'term_id'          => 152354,
		'name'             => 'HDMV Text',
		'slug'             => 'cutemi-text-format-hdmv-text',
		'term_group'       => 0,
		'term_taxonomy_id' => 152241,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'HDMV Text subtitle',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	16 => array(
		'term_id'          => 159240,
		'name'             => 'IMSC',
		'slug'             => 'cutemi-text-format-imsc',
		'term_group'       => 0,
		'term_taxonomy_id' => 159127,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'Text and Image Profiles for Internet Media Subtitles and Captions',
		'parent'           => 'cutemi-text-format-ttml',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	17 => array(
		'term_id'          => 152355,
		'name'             => 'JACOsub',
		'slug'             => 'cutemi-text-format-jacosub',
		'term_group'       => 0,
		'term_taxonomy_id' => 152242,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'JACOsub subtitle',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	18 => array(
		'term_id'          => 159230,
		'name'             => 'KATE',
		'slug'             => 'cutemi-text-format-kate',
		'term_group'       => 0,
		'term_taxonomy_id' => 159117,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'Karaoke And Text Encapsulation',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	19 => array(
		'term_id'          => 152356,
		'name'             => 'MicroDVD',
		'slug'             => 'cutemi-text-format-microdvd',
		'term_group'       => 0,
		'term_taxonomy_id' => 152243,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'MicroDVD subtitle',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	20 => array(
		'term_id'          => 152357,
		'name'             => 'MOV text',
		'slug'             => 'cutemi-text-format-mov-text',
		'term_group'       => 0,
		'term_taxonomy_id' => 152244,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'MOV text',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	21 => array(
		'term_id'          => 159255,
		'name'             => 'MP4TT',
		'slug'             => 'cutemi-text-format-mp4tt',
		'term_group'       => 0,
		'term_taxonomy_id' => 159142,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'MPEG-4 Timed Text',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)TTXT,(?i)TX3G',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	22 => array(
		'term_id'          => 152358,
		'name'             => 'MPL2',
		'slug'             => 'cutemi-text-format-mpl2',
		'term_group'       => 0,
		'term_taxonomy_id' => 152245,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'MPL2 subtitle',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	23 => array(
		'term_id'          => 152359,
		'name'             => 'PJS',
		'slug'             => 'cutemi-text-format-pjs',
		'term_group'       => 0,
		'term_taxonomy_id' => 152246,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'PJS (Phoenix Japanimation Society) subtitle',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	24 => array(
		'term_id'          => 152360,
		'name'             => 'RealText',
		'slug'             => 'cutemi-text-format-realtext',
		'term_group'       => 0,
		'term_taxonomy_id' => 152247,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'RealText subtitle',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	25 => array(
		'term_id'          => 152361,
		'name'             => 'SAMI',
		'slug'             => 'cutemi-text-format-sami',
		'term_group'       => 0,
		'term_taxonomy_id' => 152248,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'SAMI subtitle',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	26 => array(
		'term_id'          => 159238,
		'name'             => 'SDP-US',
		'slug'             => 'cutemi-text-format-sdp-us',
		'term_group'       => 0,
		'term_taxonomy_id' => 159125,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'The Simple Online Delivery Profile',
		'parent'           => 'cutemi-text-format-ttml',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	27 => array(
		'term_id'          => 159235,
		'name'             => 'SMPTE-TT',
		'slug'             => 'cutemi-text-format-smpte-tt',
		'term_group'       => 0,
		'term_taxonomy_id' => 159122,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'The SMPTE Timed Text Format',
		'parent'           => 'cutemi-text-format-ttml',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	28 => array(
		'term_id'          => 152362,
		'name'             => 'SRT',
		'slug'             => 'cutemi-text-format-srt',
		'term_group'       => 0,
		'term_taxonomy_id' => 152249,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'SubRip subtitle (srt)',
		'parent'           => 0,
		'count'            => 2,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	29 => array(
		'term_id'          => 152363,
		'name'             => 'SSA',
		'slug'             => 'cutemi-text-format-ssa',
		'term_group'       => 0,
		'term_taxonomy_id' => 152250,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'SSA (SubStation Alpha) subtitle',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	30 => array(
		'term_id'          => 152364,
		'name'             => 'STL',
		'slug'             => 'cutemi-text-format-stl',
		'term_group'       => 0,
		'term_taxonomy_id' => 152251,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'Spruce subtitle format',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	31 => array(
		'term_id'          => 152365,
		'name'             => 'SubViewer',
		'slug'             => 'cutemi-text-format-subviewer',
		'term_group'       => 0,
		'term_taxonomy_id' => 152252,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'SubViewer subtitle',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	32 => array(
		'term_id'          => 159274,
		'name'             => 'SVCD',
		'slug'             => 'cutemi-text-format-svcd',
		'term_group'       => 0,
		'term_taxonomy_id' => 159161,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'Philips Overlay Graphics Text or OGT',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)Philips Overlay Graphics Text,(?i)OGT',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	33 => array(
		'term_id'          => 159233,
		'name'             => 'Teletext',
		'slug'             => 'cutemi-text-format-teletext',
		'term_group'       => 0,
		'term_taxonomy_id' => 159120,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'CCIR Teletext System B',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	34 => array(
		'term_id'          => 159232,
		'name'             => 'TTML',
		'slug'             => 'cutemi-text-format-ttml',
		'term_group'       => 0,
		'term_taxonomy_id' => 159119,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'Timed Text Markup Language',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	35 => array(
		'term_id'          => 152366,
		'name'             => 'TXT',
		'slug'             => 'cutemi-text-format-raw',
		'term_group'       => 0,
		'term_taxonomy_id' => 152253,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'raw UTF-8 text',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	36 => array(
		'term_id'          => 159256,
		'name'             => 'USF',
		'slug'             => 'cutemi-text-format-usf',
		'term_group'       => 0,
		'term_taxonomy_id' => 159143,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'Universal Subtitle Format',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)Universal Subtitle Format,(?i)USF',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	37 => array(
		'term_id'          => 159253,
		'name'             => 'VobSub',
		'slug'             => 'cutemi-text-format-vobsub',
		'term_group'       => 0,
		'term_taxonomy_id' => 159140,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'VobSub subtitle',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)VobSub',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	38 => array(
		'term_id'          => 152367,
		'name'             => 'VPlayer',
		'slug'             => 'cutemi-text-format-vplayer',
		'term_group'       => 0,
		'term_taxonomy_id' => 152254,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'VPlayer subtitle',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	39 => array(
		'term_id'          => 152368,
		'name'             => 'WebVTT',
		'slug'             => 'cutemi-text-format-webvtt',
		'term_group'       => 0,
		'term_taxonomy_id' => 152255,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'WebVTT subtitle',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	40 => array(
		'term_id'          => 152369,
		'name'             => 'XSUB',
		'slug'             => 'cutemi-text-format-xsub',
		'term_group'       => 0,
		'term_taxonomy_id' => 152256,
		'taxonomy'         => 'cutemi_text_format',
		'description'      => 'XSUB',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
);
