<?php

$cutemi_taxonomies['cutemi_file_format'] = array(
	0  => array(
		'term_id'          => 152278,
		'name'             => '3G2',
		'slug'             => 'cutemi-file-format-3g2',
		'term_group'       => 0,
		'term_taxonomy_id' => 152165,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => '3GPP2 file format',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.3g2(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	1  => array(
		'term_id'          => 152277,
		'name'             => '3GP',
		'slug'             => 'cutemi-file-format-3gp',
		'term_group'       => 0,
		'term_taxonomy_id' => 152164,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => '3GPP file format',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.3gp(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	2  => array(
		'term_id'          => 152280,
		'name'             => 'AVI',
		'slug'             => 'cutemi-file-format-avi',
		'term_group'       => 0,
		'term_taxonomy_id' => 152167,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'Audio Video Interleave',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.avi(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '2',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	3  => array(
		'term_id'          => 152281,
		'name'             => 'DIVX',
		'slug'             => 'cutemi-file-format-divx',
		'term_group'       => 0,
		'term_taxonomy_id' => 152168,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'DivX Media Format',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.DIVX(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	4  => array(
		'term_id'          => 159241,
		'name'             => 'DVR-MS',
		'slug'             => 'cutemi-file-format-dvr-ms',
		'term_group'       => 0,
		'term_taxonomy_id' => 159128,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'Microsoft Digital Video Recording',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	5  => array(
		'term_id'          => 152282,
		'name'             => 'EVO',
		'slug'             => 'cutemi-file-format-evo',
		'term_group'       => 0,
		'term_taxonomy_id' => 152169,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'Enhanced Video Object, Enhanced EVO',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.evo(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	6  => array(
		'term_id'          => 152283,
		'name'             => 'F4V',
		'slug'             => 'cutemi-file-format-f4v',
		'term_group'       => 0,
		'term_taxonomy_id' => 152170,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'Flash media container',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.f4v(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	7  => array(
		'term_id'          => 152284,
		'name'             => 'FLV',
		'slug'             => 'cutemi-file-format-flv',
		'term_group'       => 0,
		'term_taxonomy_id' => 152171,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'Macromedia Flash Video',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.flv(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	8  => array(
		'term_id'          => 152297,
		'name'             => 'M2TS',
		'slug'             => 'cutemi-file-format-m2ts',
		'term_group'       => 0,
		'term_taxonomy_id' => 152184,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'MPEG-2 Transport Stream (M2TS, MTS)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.m2ts(\\.rar|\\.zip|\\.7z|)$,(?i)\\.mts(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '2',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	9  => array(
		'term_id'          => 159157,
		'name'             => 'M4V',
		'slug'             => 'cutemi-file-format-m4v',
		'term_group'       => 0,
		'term_taxonomy_id' => 159044,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'MPEG-4  Apple Video',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)m4v(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	10 => array(
		'term_id'          => 152287,
		'name'             => 'MCF',
		'slug'             => 'cutemi-file-format-mcf',
		'term_group'       => 0,
		'term_taxonomy_id' => 152174,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'Multimedia Container Format',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.MCF(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	11 => array(
		'term_id'          => 152285,
		'name'             => 'MKV',
		'slug'             => 'cutemi-file-format-mkv',
		'term_group'       => 0,
		'term_taxonomy_id' => 152172,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'Matroska multimedia container',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.MKV(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '4',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	12 => array(
		'term_id'          => 152292,
		'name'             => 'MOV',
		'slug'             => 'cutemi-file-format-mov',
		'term_group'       => 0,
		'term_taxonomy_id' => 152179,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'QuickTime File Format (QTFF)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.mov(\\.rar|\\.zip|\\.7z|)$,(?i)\\.qt(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	13 => array(
		'term_id'          => 152288,
		'name'             => 'MP4',
		'slug'             => 'cutemi-file-format-mp4',
		'term_group'       => 0,
		'term_taxonomy_id' => 152175,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'MPEG-4 Part 14',
		'parent'           => 0,
		'count'            => 2,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)mp4(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '5',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	14 => array(
		'term_id'          => 152289,
		'name'             => 'MPEG',
		'slug'             => 'cutemi-file-format-mpeg',
		'term_group'       => 0,
		'term_taxonomy_id' => 152176,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'MPEG Video File',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.MPE?G(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	15 => array(
		'term_id'          => 152290,
		'name'             => 'MXF',
		'slug'             => 'cutemi-file-format-mxf',
		'term_group'       => 0,
		'term_taxonomy_id' => 152177,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'Material eXchange Format',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.mxf(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	16 => array(
		'term_id'          => 152291,
		'name'             => 'OGG',
		'slug'             => 'cutemi-file-format-ogg',
		'term_group'       => 0,
		'term_taxonomy_id' => 152178,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => '.ogg, .ogv, .ogx, .ogm, .spx, .opus..',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.ogg(\\.rar|\\.zip|\\.7z|),$(?i)\\.ogv(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	17 => array(
		'term_id'          => 152295,
		'name'             => 'PS',
		'slug'             => 'cutemi-file-format-ps',
		'term_group'       => 0,
		'term_taxonomy_id' => 152182,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'MPEG program stream PS (.m2p, .ps)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.ps(\\.rar|\\.zip|\\.7z|)$,(?i)\\.m2p(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	18 => array(
		'term_id'          => 152293,
		'name'             => 'RMVB',
		'slug'             => 'cutemi-file-format-rmvb',
		'term_group'       => 0,
		'term_taxonomy_id' => 152180,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'RealMedia Variable Bitrate',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.RMVB(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	19 => array(
		'term_id'          => 152296,
		'name'             => 'TS',
		'slug'             => 'cutemi-file-format-ts',
		'term_group'       => 0,
		'term_taxonomy_id' => 152183,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'MPEG transport stream (.ts, .tsv, .tsa)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.ts(\\.rar|\\.zip|\\.7z|)$,(?i)\\.tsv(\\.rar|\\.zip|\\.7z|)$,(?i)\\.tsa(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	20 => array(
		'term_id'          => 152294,
		'name'             => 'VOB',
		'slug'             => 'cutemi-file-format-vob',
		'term_group'       => 0,
		'term_taxonomy_id' => 152181,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'VOB+IFO (Video Object + Information Files)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.vob(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	21 => array(
		'term_id'          => 152286,
		'name'             => 'WEBM',
		'slug'             => 'cutemi-file-format-webm',
		'term_group'       => 0,
		'term_taxonomy_id' => 152173,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'WebM container',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.webm(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	22 => array(
		'term_id'          => 152279,
		'name'             => 'WMV',
		'slug'             => 'cutemi-file-format-wmv',
		'term_group'       => 0,
		'term_taxonomy_id' => 152166,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'Advanced Streaming Format',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)\\.wmv(\\.rar|\\.zip|\\.7z|)$,(?i)\\.asf(\\.rar|\\.zip|\\.7z|)$',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	23 => array(
		'term_id'          => 159242,
		'name'             => 'WTV',
		'slug'             => 'cutemi-file-format-wtv',
		'term_group'       => 0,
		'term_taxonomy_id' => 159129,
		'taxonomy'         => 'cutemi_file_format',
		'description'      => 'Windows Recorded TV Show',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
);
