<?php

$cutemi_taxonomies['cutemi_audio_channels'] = array(
	0  => array(
		'term_id'          => 152254,
		'name'             => '1.0',
		'slug'             => 'cutemi-audio-channels-1-0',
		'term_group'       => 0,
		'term_taxonomy_id' => 152141,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Mono',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '10',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	1  => array(
		'term_id'          => 159193,
		'name'             => '11',
		'slug'             => 'cutemi-audio-channels-11-0',
		'term_group'       => 0,
		'term_taxonomy_id' => 159080,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Eleven channel output',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '110',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	2  => array(
		'term_id'          => 159194,
		'name'             => '11.1',
		'slug'             => 'cutemi-audio-channels-11-1',
		'term_group'       => 0,
		'term_taxonomy_id' => 159081,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Eleven channel output, plus subwoofer',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '111',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	3  => array(
		'term_id'          => 152255,
		'name'             => '2.0',
		'slug'             => 'cutemi-audio-channels-2-0',
		'term_group'       => 0,
		'term_taxonomy_id' => 152142,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Stereo',
		'parent'           => 0,
		'count'            => 2,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => 'AAC(?: |-|\\.|)2\\.0,DDP(?: |-|\\.|)2\\.0,DTS(?: |-|\\.|)HD(?: |-|\\.|)MA(?: |-|\\.|)2\\.0',
			'priority_sum'    => '20',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	4  => array(
		'term_id'          => 152256,
		'name'             => '2.1',
		'slug'             => 'cutemi-audio-channels-2-1',
		'term_group'       => 0,
		'term_taxonomy_id' => 152143,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Two-channel output, plus a subwoofer',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '21',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	5  => array(
		'term_id'          => 159187,
		'name'             => '3.0',
		'slug'             => 'cutemi-audio-channels-3-0',
		'term_group'       => 0,
		'term_taxonomy_id' => 159074,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Three channel output',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '30',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	6  => array(
		'term_id'          => 159188,
		'name'             => '3.1',
		'slug'             => 'cutemi-audio-channels-3-1',
		'term_group'       => 0,
		'term_taxonomy_id' => 159075,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Three channel output, plus subwoofer',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '31',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	7  => array(
		'term_id'          => 159189,
		'name'             => '4.0',
		'slug'             => 'cutemi-audio-channels-4-0',
		'term_group'       => 0,
		'term_taxonomy_id' => 159076,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Four channel output',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '40',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	8  => array(
		'term_id'          => 159190,
		'name'             => '4.1',
		'slug'             => 'cutemi-audio-channels-4-1',
		'term_group'       => 0,
		'term_taxonomy_id' => 159077,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Four channel output, plus subwoofer',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '41',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	9  => array(
		'term_id'          => 152258,
		'name'             => '5.0',
		'slug'             => 'cutemi-audio-channels-5-0',
		'term_group'       => 0,
		'term_taxonomy_id' => 152145,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Five channel output',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '50',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	10 => array(
		'term_id'          => 152257,
		'name'             => '5.1',
		'slug'             => 'cutemi-audio-channels-5-1',
		'term_group'       => 0,
		'term_taxonomy_id' => 152144,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Five channel output, plus subwoofer',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)DTS(?: |-|\\.|)HD(?: |-|\\.|)MA(?: |-|\\.|)5(?: |-|\\.|)1, (?i)DD5(?: |-|\\.|)1,.DTS(?: |-|\\.|)HR(?: |-|\\.|)5\\.1',
			'priority_sum'    => '51',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	11 => array(
		'term_id'          => 159191,
		'name'             => '6.0',
		'slug'             => 'cutemi-audio-channels-6-0',
		'term_group'       => 0,
		'term_taxonomy_id' => 159078,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Six channel output',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '60',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	12 => array(
		'term_id'          => 159192,
		'name'             => '6.1',
		'slug'             => 'cutemi-audio-channels-6-1',
		'term_group'       => 0,
		'term_taxonomy_id' => 159079,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Six channel output, plus subwoofer',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '61',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	13 => array(
		'term_id'          => 159227,
		'name'             => '7.0',
		'slug'             => 'cutemi-audio-channels-7-0',
		'term_group'       => 0,
		'term_taxonomy_id' => 159114,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Seven channel output',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '70',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	14 => array(
		'term_id'          => 152259,
		'name'             => '7.1',
		'slug'             => 'cutemi-audio-channels-7-1',
		'term_group'       => 0,
		'term_taxonomy_id' => 152146,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Seven channel output, plus subwoofer',
		'parent'           => 0,
		'count'            => 2,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => 'DTS-HD.MA.7.1,DTS-HD.MA.TrueHD.7.1',
			'priority_sum'    => '71',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	15 => array(
		'term_id'          => 159195,
		'name'             => '8.0',
		'slug'             => 'cutemi-audio-channels-8-0',
		'term_group'       => 0,
		'term_taxonomy_id' => 159082,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Eight channel output',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '80',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	16 => array(
		'term_id'          => 159196,
		'name'             => '8.1',
		'slug'             => 'cutemi-audio-channels-8-1',
		'term_group'       => 0,
		'term_taxonomy_id' => 159083,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Eight channel output, plus subwoofer

',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '81',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	17 => array(
		'term_id'          => 159228,
		'name'             => '9.0',
		'slug'             => 'cutemi-audio-channels-9-0',
		'term_group'       => 0,
		'term_taxonomy_id' => 159115,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Nine channel output',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '90',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	18 => array(
		'term_id'          => 152267,
		'name'             => '9.1',
		'slug'             => 'cutemi-audio-channels-9-1',
		'term_group'       => 0,
		'term_taxonomy_id' => 152154,
		'taxonomy'         => 'cutemi_audio_channels',
		'description'      => 'Nine channel output, plus subwoofer',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => 'DTS-HD.MA.9.1,DTS-HD.MA.TrueHD.9.1',
			'priority_sum'    => '91',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
);
