<?php

$cutemi_taxonomies['cutemi_audio_tech'] = array(
	0  => array(
		'term_id'          => 152030,
		'name'             => 'AAC',
		'slug'             => 'cutemi-audio-tech-aac',
		'term_group'       => 0,
		'term_taxonomy_id' => 151917,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Advanced Audio Coding',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)ACC,(?i)AAC(?: |-|\\.|)LC,(?i)Advanced Audio Cod(ing|ec)',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	1  => array(
		'term_id'          => 159271,
		'name'             => 'ADPCM',
		'slug'             => 'cutemi-audio-tech-adpcm',
		'term_group'       => 0,
		'term_taxonomy_id' => 159158,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Adaptive differential pulse-code modulation',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)ADPCM',
			'priority_sum'    => '0',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	2  => array(
		'term_id'          => 152268,
		'name'             => 'AIFF',
		'slug'             => 'cutemi-audio-tech-aiff',
		'term_group'       => 0,
		'term_taxonomy_id' => 152155,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Interchange File Format',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)AIFF',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	3  => array(
		'term_id'          => 152269,
		'name'             => 'AIFF-C',
		'slug'             => 'cutemi-audio-tech-aiffc',
		'term_group'       => 0,
		'term_taxonomy_id' => 152156,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Compressed Interchange File Format ',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => 'aiff(?: |-|\\.|)c',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	4  => array(
		'term_id'          => 152270,
		'name'             => 'ALAC',
		'slug'             => 'cutemi-audio-tech-alac',
		'term_group'       => 0,
		'term_taxonomy_id' => 152157,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Apple Lossless Audio Codec',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)ALAC',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	5  => array(
		'term_id'          => 152271,
		'name'             => 'CDDA',
		'slug'             => 'cutemi-audio-tech-cdda',
		'term_group'       => 0,
		'term_taxonomy_id' => 152158,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Compact Disc Digital Audio',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)cdda',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	6  => array(
		'term_id'          => 152041,
		'name'             => 'Dolby AC-4',
		'slug'             => 'cutemi-audio-tech-dolby-ac-4',
		'term_group'       => 0,
		'term_taxonomy_id' => 151928,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Dolby Audio Codec 4',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)AC(?: |-|\\.|)4',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	7  => array(
		'term_id'          => 152038,
		'name'             => 'Dolby Digital',
		'slug'             => 'cutemi-audio-tech-dolby-digital',
		'term_group'       => 0,
		'term_taxonomy_id' => 151925,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'AC-3, Audio Codec 3',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)AC(?: |-|\\.|)3, (?i)DD(?: |-|\\.|)5\\.1, (?i)DD(?: |-|\\.|)2\\.0, (?i)SR(?: |-|\\.|)Digital, (?i)SR(?: |-|\\.|)D, (?i)Audio(?: |-|\\.|)Codec(?: |-|\\.|)3, (?i)Acoustic(?: |-|\\.|)Codec(?: |-|\\.|)3, (?i)ATSC(?: |-|\\.|)A/52',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	8  => array(
		'term_id'          => 152039,
		'name'             => 'Dolby Digital EX',
		'slug'             => 'cutemi-audio-tech-dolby-digital-ex',
		'term_group'       => 0,
		'term_taxonomy_id' => 151926,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Dolby Digital EX',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)Dolby(?: |-|\\.|)Digital(?: |-|\\.|)EX',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	9  => array(
		'term_id'          => 152040,
		'name'             => 'Dolby Digital Plus',
		'slug'             => 'cutemi-audio-tech-dolby-digital-plus',
		'term_group'       => 0,
		'term_taxonomy_id' => 151927,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'DD+, AC3+ o E-AC-3 (Enhanced AC-3)',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)DD\\+, (?i)DDP, (?i)DDP5\\.1, (?i)AC3\\+, (?i)E(?: |-|\\.|)AC(?: |-|\\.|)3,(?i)Enhanced(?: |-|\\.|)AC(?: |-|\\.|)3',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	10 => array(
		'term_id'          => 152044,
		'name'             => 'Dolby Digital Plus with Atmos',
		'slug'             => 'cutemi-audio-tech-dolby-digital-plus-atmos',
		'term_group'       => 0,
		'term_taxonomy_id' => 151931,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Dolby Digital Plus + Atmos',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)Atmos(?: |-|\\.|)DDP,(?i)Atmos(?: |-|\\.|)DDP5',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	11 => array(
		'term_id'          => 152042,
		'name'             => 'Dolby TrueHD',
		'slug'             => 'cutemi-audio-tech-dolby-truehd',
		'term_group'       => 0,
		'term_taxonomy_id' => 151929,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Dolby TrueHD, MLP',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)TrueHD,(?i)THD',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	12 => array(
		'term_id'          => 152043,
		'name'             => 'Dolby TrueHD with Atmos',
		'slug'             => 'cutemi-audio-tech-dolby-truehd-with-atoms',
		'term_group'       => 0,
		'term_taxonomy_id' => 151930,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Dolby TrueHD + Atmos',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)THD(?: |\\+|\\.|)A,(?i)Atmos(?: |-|\\.|)TrueHD(?: |-|5|7|)',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	13 => array(
		'term_id'          => 159273,
		'name'             => 'DSD',
		'slug'             => 'cutemi-audio-tech-dsd',
		'term_group'       => 0,
		'term_taxonomy_id' => 159160,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Direct Stream Digital',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)DSD,(?i)Direct Stream Digital',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	14 => array(
		'term_id'          => 152045,
		'name'             => 'DTS',
		'slug'             => 'cutemi-audio-tech-dts',
		'term_group'       => 0,
		'term_taxonomy_id' => 151932,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Digital Theater System',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)DTS',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	15 => array(
		'term_id'          => 152048,
		'name'             => 'DTS 96/24',
		'slug'             => 'cutemi-audio-tech-dts-96-24',
		'term_group'       => 0,
		'term_taxonomy_id' => 151935,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'DTS 96/24: Core + X96 Support',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)DTS(?: |-|\\.|)96(?: |-|\\.|/)24',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	16 => array(
		'term_id'          => 152046,
		'name'             => 'DTS Express',
		'slug'             => 'cutemi-audio-tech-dts-express',
		'term_group'       => 0,
		'term_taxonomy_id' => 151933,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Digital Theater System Express (LBR support)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)DTS(?: |-|\\.|)Express',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	17 => array(
		'term_id'          => 152047,
		'name'             => 'DTS-ES',
		'slug'             => 'cutemi-audio-tech-dts-es',
		'term_group'       => 0,
		'term_taxonomy_id' => 151934,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'DTS Extended Surround: Core + XCh, XXCh support',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)DTS(?: |-|\\.|)ES, (?i)DTS(?: |-|\\.|)Extended(?: |-|\\.|)Surround',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	18 => array(
		'term_id'          => 152049,
		'name'             => 'DTS-HD',
		'slug'             => 'cutemi-audio-tech-dts-hd',
		'term_group'       => 0,
		'term_taxonomy_id' => 151936,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'DTS-HD High Resolution Audio, Core + XCh + XBR support',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)DTS(?: |-|\\.|)HD',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	19 => array(
		'term_id'          => 152050,
		'name'             => 'DTS-HD MA',
		'slug'             => 'cutemi-audio-tech-dts-hd-ma',
		'term_group'       => 0,
		'term_taxonomy_id' => 151937,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'DTS-HD Master Audio, DTS XLL',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)DTS(?: |-|\\.|)HD(?: |-|\\.|)MA, (?i)DTS(?: |-|\\.|)\\+\\+, (?i)DTS(?: |-|\\.|)XLL',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	20 => array(
		'term_id'          => 152051,
		'name'             => 'DTS:X',
		'slug'             => 'cutemi-audio-tech-dts-x',
		'term_group'       => 0,
		'term_taxonomy_id' => 151938,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'DTS:X',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)DTS(?: |-|\\.|:|)X',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	21 => array(
		'term_id'          => 152032,
		'name'             => 'FLAC',
		'slug'             => 'cutemi-audio-tech-flac',
		'term_group'       => 0,
		'term_taxonomy_id' => 151919,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Free Lossless Audio Codec',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i:)FLAC',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	22 => array(
		'term_id'          => 152031,
		'name'             => 'HE-AAC',
		'slug'             => 'cutemi-audio-tech-he-acc',
		'term_group'       => 0,
		'term_taxonomy_id' => 151918,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'High-Efficiency Advanced Audio Coding',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)HE(?: |-|\\.|)AAC',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	23 => array(
		'term_id'          => 152037,
		'name'             => 'LPCM',
		'slug'             => 'cutemi-audio-tech-lpcm',
		'term_group'       => 0,
		'term_taxonomy_id' => 151924,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Linear Pulse Code Modulation',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)L(?: |-|\\.|)PCM',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	24 => array(
		'term_id'          => 159244,
		'name'             => 'MP2',
		'slug'             => 'cutemi-audio-tech-mp2',
		'term_group'       => 0,
		'term_taxonomy_id' => 159131,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'MPEG-1 Audio Layer 2',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	25 => array(
		'term_id'          => 159243,
		'name'             => 'MP3',
		'slug'             => 'cutemi-audio-tech-mp3',
		'term_group'       => 0,
		'term_taxonomy_id' => 159130,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'MPEG Audio Layer III',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '',
			'priority_sum'    => '0',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	26 => array(
		'term_id'          => 152034,
		'name'             => 'Opus',
		'slug'             => 'cutemi-audio-tech-opus',
		'term_group'       => 0,
		'term_taxonomy_id' => 151921,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Opus',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)OPUS',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	27 => array(
		'term_id'          => 152036,
		'name'             => 'PCM',
		'slug'             => 'cutemi-audio-tech-pcm',
		'term_group'       => 0,
		'term_taxonomy_id' => 151923,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Pulse Code Modulation',
		'parent'           => 0,
		'count'            => 1,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)PCM',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	28 => array(
		'term_id'          => 159258,
		'name'             => 'Real Audio 1',
		'slug'             => 'cutemi-audio-tech-realaudio-1',
		'term_group'       => 0,
		'term_taxonomy_id' => 159145,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'RealAudio 1 (IS-54 VSELP)',
		'parent'           => 'cutemi-audio-tech-realaudio',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)RealAudio 1,(?i)lpcJ,(?i)14_4',
			'priority_sum'    => '0',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	29 => array(
		'term_id'          => 152276,
		'name'             => 'RealAudio',
		'slug'             => 'cutemi-audio-tech-realaudio',
		'term_group'       => 0,
		'term_taxonomy_id' => 152163,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => '',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)Real(?: |-|\\.|)Audio',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	30 => array(
		'term_id'          => 159265,
		'name'             => 'RealAudio 10',
		'slug'             => 'cutemi-audio-tech-realaudio-10',
		'term_group'       => 0,
		'term_taxonomy_id' => 159152,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'RealAudio 10 (MPEG-4 HE-AAC)',
		'parent'           => 'cutemi-audio-tech-realaudio',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)RealAudio 10,(?i)racp',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	31 => array(
		'term_id'          => 159266,
		'name'             => 'RealAudio 10 Lossless',
		'slug'             => 'cutemi-audio-tech-realaudio-10-lossless',
		'term_group'       => 0,
		'term_taxonomy_id' => 159153,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'RealAudio 10 (RealAudio Lossless Format)',
		'parent'           => 'cutemi-audio-tech-realaudio',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)RealAudio Lossless Format,(?i)ralf',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	32 => array(
		'term_id'          => 159259,
		'name'             => 'RealAudio 2',
		'slug'             => 'cutemi-audio-tech-realaudio-2',
		'term_group'       => 0,
		'term_taxonomy_id' => 159146,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'RealAudio 2 (G.728 LD-CELP)',
		'parent'           => 'cutemi-audio-tech-realaudio',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)RealAudio 2,(?i)28_8',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	33 => array(
		'term_id'          => 159260,
		'name'             => 'RealAudio 3',
		'slug'             => 'cutemi-audio-tech-realaudio-3',
		'term_group'       => 0,
		'term_taxonomy_id' => 159147,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'RealAudio 3 (Dolby AC3)',
		'parent'           => 'cutemi-audio-tech-realaudio',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)RealAudio 3,(?i)dnet',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	34 => array(
		'term_id'          => 159261,
		'name'             => 'RealAudio 4/5',
		'slug'             => 'cutemi-audio-tech-realaudio-4-5',
		'term_group'       => 0,
		'term_taxonomy_id' => 159148,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'RealAudio 4/5 ( Sipro Lab Telecom ACELP-NET)',
		'parent'           => 'cutemi-audio-tech-realaudio',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)RealAudio 4,(?i)RealAudio 5,(?i)sipr',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	35 => array(
		'term_id'          => 159262,
		'name'             => 'RealAudio 6',
		'slug'             => 'cutemi-audio-tech-realaudio-6',
		'term_group'       => 0,
		'term_taxonomy_id' => 159149,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'RealAudio 6 (G2/Cook Codec)',
		'parent'           => 'cutemi-audio-tech-realaudio',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)RealAudio 6,(?i)cook',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	36 => array(
		'term_id'          => 159263,
		'name'             => 'RealAudio 8',
		'slug'             => 'cutemi-audio-tech-realaudio-8',
		'term_group'       => 0,
		'term_taxonomy_id' => 159150,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'RealAudio 8 (Sony ATRAC3)',
		'parent'           => 'cutemi-audio-tech-realaudio',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)RealAudio 8,(?i)atrc',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	37 => array(
		'term_id'          => 159264,
		'name'             => 'RealAudio 9',
		'slug'             => 'cutemi-audio-tech-realaudio-9',
		'term_group'       => 0,
		'term_taxonomy_id' => 159151,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'RealAudio 9 (MPEG-4 LC-AAC)',
		'parent'           => 'cutemi-audio-tech-realaudio',
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)RealAudio 9,(?i)raac',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	38 => array(
		'term_id'          => 152033,
		'name'             => 'Vorbis',
		'slug'             => 'cutemi-audio-tech-vorbis',
		'term_group'       => 0,
		'term_taxonomy_id' => 151920,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Xiph.Org Foundation Audio (Ogg)',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)Vorbis,(?i)OGG',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	39 => array(
		'term_id'          => 152035,
		'name'             => 'WAV',
		'slug'             => 'cutemi-audio-tech-wav',
		'term_group'       => 0,
		'term_taxonomy_id' => 151922,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Waveform Audio File Format',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)WAV',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	40 => array(
		'term_id'          => 152272,
		'name'             => 'WavPack',
		'slug'             => 'cutemi-audio-tech-wavpack',
		'term_group'       => 0,
		'term_taxonomy_id' => 152159,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'WavPack',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)WavPack',
			'priority_sum'    => '0',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	41 => array(
		'term_id'          => 152273,
		'name'             => 'WMA',
		'slug'             => 'cutemi-audio-tech-wma',
		'term_group'       => 0,
		'term_taxonomy_id' => 152160,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Windows Media Audio',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)WMA',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	42 => array(
		'term_id'          => 152274,
		'name'             => 'WMA Lossless',
		'slug'             => 'cutemi-audio-tech-wma-l',
		'term_group'       => 0,
		'term_taxonomy_id' => 152161,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'WMA Lossless',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => '(?i)WMAL',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
	43 => array(
		'term_id'          => 152275,
		'name'             => 'WMA Pro',
		'slug'             => 'cutemi-audio-tech-wma-pro',
		'term_group'       => 0,
		'term_taxonomy_id' => 152162,
		'taxonomy'         => 'cutemi_audio_tech',
		'description'      => 'Windows Media Audio Pro',
		'parent'           => 0,
		'count'            => 0,
		'filter'           => 'raw',
		'metas'            => array(
			'tags'            => 'WMA(?: |-|\\.|)PRO',
			'priority_sum'    => '1',
			'image_url'       => '',
			'cutemi_disabled' => '',
		),
	),
);
