<?php

if ( ! defined( 'ABSPATH' ) ) {
	die( 'Invalid request.' );
}

function cutemi_register_taxonomies() {
	$taxonomies_wp_cute_mediainfo = array(

		'cutemi_site_source'        => array(
			'args' => array(
				'labels'             => array(
					'name'                       => _x( 'Link Source', 'Taxonomy General Name', 'cute-mediainfo' ),
					'singular_name'              => _x( 'Link Source', 'Taxonomy Singular Name', 'cute-mediainfo' ),
					'menu_name'                  => __( 'Link Sources', 'cute-mediainfo' ),
					'all_items'                  => __( 'All Sources', 'cute-mediainfo' ),
					'parent_item'                => __( 'Parent Source', 'cute-mediainfo' ),
					'parent_item_colon'          => __( 'Parent Source:', 'cute-mediainfo' ),
					'new_item_name'              => __( 'New Link Source Name', 'cute-mediainfo' ),
					'add_new_item'               => __( 'Add New Link Source', 'cute-mediainfo' ),
					'edit_item'                  => __( 'Edit Link Source', 'cute-mediainfo' ),
					'update_item'                => __( 'Update Link Source', 'cute-mediainfo' ),
					'view_item'                  => __( 'View Link Source', 'cute-mediainfo' ),
					'separate_items_with_commas' => __( 'Separate items with commas', 'cute-mediainfo' ),
					'add_or_remove_items'        => __( 'Add or remove Link Sources', 'cute-mediainfo' ),
					'choose_from_most_used'      => __( 'Choose from the most used', 'cute-mediainfo' ),
					'popular_items'              => __( 'Popular Link Sources', 'cute-mediainfo' ),
					'search_items'               => __( 'Search Link Sources', 'cute-mediainfo' ),
					'not_found'                  => __( 'Not Found', 'cute-mediainfo' ),
					'no_terms'                   => __( 'No Link Sources', 'cute-mediainfo' ),
					'items_list'                 => __( 'Items list', 'cute-mediainfo' ),
					'items_list_navigation'      => __( 'Items list navigation', 'cute-mediainfo' ),
				),
				'hierarchical'       => false,
				'public'             => false,
				'show_ui'            => true,
				'show_in_quick_edit' => false,
				'show_admin_column'  => false,
				'show_in_nav_menus'  => false,
				'show_tagcloud'      => false,
				'rewrite'            => false,
				'show_in_rest'       => false,
				'meta_box_cb'        => false,
			),
		),

		'cutemi_video_resolution'   => array(
			'args' => array(
				'labels'             => array(
					'name'                       => _x( 'Video Resolution', 'Taxonomy General Name', 'cute-mediainfo' ),
					'singular_name'              => _x( 'Video Resolution', 'Taxonomy Singular Name', 'cute-mediainfo' ),
					'menu_name'                  => __( 'Video Resolutions', 'cute-mediainfo' ),
					'all_items'                  => __( 'All Video Resolutions', 'cute-mediainfo' ),
					'parent_item'                => __( 'Parent Video Resolution', 'cute-mediainfo' ),
					'parent_item_colon'          => __( 'Parent Video Resolution:', 'cute-mediainfo' ),
					'new_item_name'              => __( 'New Video Resolution Name', 'cute-mediainfo' ),
					'add_new_item'               => __( 'Add New Video Resolution', 'cute-mediainfo' ),
					'edit_item'                  => __( 'Edit Video Resolution', 'cute-mediainfo' ),
					'update_item'                => __( 'Update Video Resolution', 'cute-mediainfo' ),
					'view_item'                  => __( 'View Video Resolution', 'cute-mediainfo' ),
					'separate_items_with_commas' => __( 'Separate Video Resolutions with commas', 'cute-mediainfo' ),
					'add_or_remove_items'        => __( 'Add or remove Video Resolutions', 'cute-mediainfo' ),
					'choose_from_most_used'      => __( 'Choose from the most used', 'cute-mediainfo' ),
					'popular_items'              => __( 'Popular Video Resolutions', 'cute-mediainfo' ),
					'search_items'               => __( 'Search Video Resolutions', 'cute-mediainfo' ),
					'not_found'                  => __( 'Not Found', 'cute-mediainfo' ),
					'no_terms'                   => __( 'No Video Resolutions', 'cute-mediainfo' ),
					'items_list'                 => __( 'Items list', 'cute-mediainfo' ),
					'items_list_navigation'      => __( 'Items list navigation', 'cute-mediainfo' ),
				),
				'hierarchical'       => true,
				'public'             => false,
				'show_ui'            => true,
				'show_in_quick_edit' => false,
				'show_admin_column'  => false,
				'show_in_nav_menus'  => false,
				'show_tagcloud'      => false,
				'rewrite'            => false,
				'show_in_rest'       => false,
				'meta_box_cb'        => false,
			),
		),

		'cutemi_video_bitrate'      => array(
			'args' => array(
				'labels'             => array(
					'name'                       => _x( 'Video Bitrate', 'Taxonomy General Name', 'cute-mediainfo' ),
					'singular_name'              => _x( 'Video Bitrate', 'Taxonomy Singular Name', 'cute-mediainfo' ),
					'menu_name'                  => __( 'Video Bitrates', 'cute-mediainfo' ),
					'all_items'                  => __( 'All Items', 'cute-mediainfo' ),
					'parent_item'                => __( 'Parent Video Bitrate', 'cute-mediainfo' ),
					'parent_item_colon'          => __( 'Parent Video Bitrate:', 'cute-mediainfo' ),
					'new_item_name'              => __( 'New Video Bitrate Name', 'cute-mediainfo' ),
					'add_new_item'               => __( 'Add New Video Bitrate', 'cute-mediainfo' ),
					'edit_item'                  => __( 'Edit Video Bitrate', 'cute-mediainfo' ),
					'update_item'                => __( 'Update Video Bitrate', 'cute-mediainfo' ),
					'view_item'                  => __( 'View Video Bitrate', 'cute-mediainfo' ),
					'separate_items_with_commas' => __( 'Separate Video Bitrates with commas', 'cute-mediainfo' ),
					'add_or_remove_items'        => __( 'Add or remove Video Bitrates', 'cute-mediainfo' ),
					'choose_from_most_used'      => __( 'Choose from the most used', 'cute-mediainfo' ),
					'popular_items'              => __( 'Popular Video Bitrates', 'cute-mediainfo' ),
					'search_items'               => __( 'Search Video Bitrates', 'cute-mediainfo' ),
					'not_found'                  => __( 'Not Found', 'cute-mediainfo' ),
					'no_terms'                   => __( 'No Video Bitrates', 'cute-mediainfo' ),
					'items_list'                 => __( 'Items list', 'cute-mediainfo' ),
					'items_list_navigation'      => __( 'Items list navigation', 'cute-mediainfo' ),
				),
				'hierarchical'       => false,
				'public'             => false,
				'show_ui'            => true,
				'show_in_quick_edit' => false,
				'show_admin_column'  => false,
				'show_in_nav_menus'  => false,
				'show_tagcloud'      => false,
				'rewrite'            => false,
				'show_in_rest'       => false,
				'meta_box_cb'        => false,
			),
		),

		'cutemi_video_bitrate_mode' => array(
			'args' => array(
				'labels'             => array(
					'name'                       => _x( 'Video Bitrate Mode', 'Taxonomy General Name', 'cute-mediainfo' ),
					'singular_name'              => _x( 'Video Bitrate Mode', 'Taxonomy Singular Name', 'cute-mediainfo' ),
					'menu_name'                  => __( 'Video Bitrate Modes', 'cute-mediainfo' ),
					'all_items'                  => __( 'All Items', 'cute-mediainfo' ),
					'parent_item'                => __( 'Parent Video Bitrate Mode', 'cute-mediainfo' ),
					'parent_item_colon'          => __( 'Parent Video Bitrate Mode:', 'cute-mediainfo' ),
					'new_item_name'              => __( 'New Video Bitrate Mode Name', 'cute-mediainfo' ),
					'add_new_item'               => __( 'Add New Video Bitrate Mode', 'cute-mediainfo' ),
					'edit_item'                  => __( 'Edit Video Bitrate Mode', 'cute-mediainfo' ),
					'update_item'                => __( 'Update Video Bitrate Mode', 'cute-mediainfo' ),
					'view_item'                  => __( 'View Video Bitrate Mode', 'cute-mediainfo' ),
					'separate_items_with_commas' => __( 'Separate Video Bitrate Modes with commas', 'cute-mediainfo' ),
					'add_or_remove_items'        => __( 'Add or remove Video Bitrate Modes', 'cute-mediainfo' ),
					'choose_from_most_used'      => __( 'Choose from the most used', 'cute-mediainfo' ),
					'popular_items'              => __( 'Popular Video Bitrate Modes', 'cute-mediainfo' ),
					'search_items'               => __( 'Search Video Bitrate Modes', 'cute-mediainfo' ),
					'not_found'                  => __( 'Not Found', 'cute-mediainfo' ),
					'no_terms'                   => __( 'No Video Bitrate Modes', 'cute-mediainfo' ),
					'items_list'                 => __( 'Items list', 'cute-mediainfo' ),
					'items_list_navigation'      => __( 'Items list navigation', 'cute-mediainfo' ),
				),
				'hierarchical'       => false,
				'public'             => false,
				'show_ui'            => true,
				'show_in_quick_edit' => false,
				'show_admin_column'  => false,
				'show_in_nav_menus'  => false,
				'show_tagcloud'      => false,
				'rewrite'            => false,
				'show_in_rest'       => false,
				'meta_box_cb'        => false,
			),
		),

		'cutemi_audio_tech'         => array(
			'args' => array(
				'labels'             => array(
					'name'                       => _x( 'Audio Tech', 'Taxonomy General Name', 'cute-mediainfo' ),
					'singular_name'              => _x( 'Audio Tech', 'Taxonomy Singular Name', 'cute-mediainfo' ),
					'menu_name'                  => __( 'Audio Techs', 'cute-mediainfo' ),
					'all_items'                  => __( 'All Audio Techs', 'cute-mediainfo' ),
					'parent_item'                => __( 'Parent Audio Tech', 'cute-mediainfo' ),
					'parent_item_colon'          => __( 'Parent Audio Tech:', 'cute-mediainfo' ),
					'new_item_name'              => __( 'New Audio Tech Name', 'cute-mediainfo' ),
					'add_new_item'               => __( 'Add New Audio Tech', 'cute-mediainfo' ),
					'edit_item'                  => __( 'Edit Audio Tech', 'cute-mediainfo' ),
					'update_item'                => __( 'Update Audio Tech', 'cute-mediainfo' ),
					'view_item'                  => __( 'View Audio Tech', 'cute-mediainfo' ),
					'separate_items_with_commas' => __( 'Separate Audio Techs with commas', 'cute-mediainfo' ),
					'add_or_remove_items'        => __( 'Add or remove Audio Techs', 'cute-mediainfo' ),
					'choose_from_most_used'      => __( 'Choose from the most used', 'cute-mediainfo' ),
					'popular_items'              => __( 'Popular Audio Techs', 'cute-mediainfo' ),
					'search_items'               => __( 'Search Audio Techs', 'cute-mediainfo' ),
					'not_found'                  => __( 'Not Found', 'cute-mediainfo' ),
					'no_terms'                   => __( 'No Audio Techs', 'cute-mediainfo' ),
					'items_list'                 => __( 'Items list', 'cute-mediainfo' ),
					'items_list_navigation'      => __( 'Items list navigation', 'cute-mediainfo' ),
				),
				'hierarchical'       => true,
				'public'             => false,
				'show_ui'            => true,
				'show_in_quick_edit' => false,
				'show_admin_column'  => false,
				'show_in_nav_menus'  => false,
				'show_tagcloud'      => false,
				'rewrite'            => false,
				'show_in_rest'       => false,
				'meta_box_cb'        => false,
			),
		),

		'cutemi_audio_channels'     => array(
			'args' => array(
				'labels'             => array(
					'name'                       => _x( 'Audio Channel', 'Taxonomy General Name', 'cute-mediainfo' ),
					'singular_name'              => _x( 'Audio Channel', 'Taxonomy Singular Name', 'cute-mediainfo' ),
					'menu_name'                  => __( 'Audio Channels', 'cute-mediainfo' ),
					'all_items'                  => __( 'All Items', 'cute-mediainfo' ),
					'parent_item'                => __( 'Parent Audio Channel', 'cute-mediainfo' ),
					'parent_item_colon'          => __( 'Parent Audio Channel:', 'cute-mediainfo' ),
					'new_item_name'              => __( 'New Audio Channel Name', 'cute-mediainfo' ),
					'add_new_item'               => __( 'Add New Audio Channel', 'cute-mediainfo' ),
					'edit_item'                  => __( 'Edit Audio Channel', 'cute-mediainfo' ),
					'update_item'                => __( 'Update Audio Channel', 'cute-mediainfo' ),
					'view_item'                  => __( 'View Audio Channel', 'cute-mediainfo' ),
					'separate_items_with_commas' => __( 'Separate Audio Channels with commas', 'cute-mediainfo' ),
					'add_or_remove_items'        => __( 'Add or remove Audio Channels', 'cute-mediainfo' ),
					'choose_from_most_used'      => __( 'Choose from the most used', 'cute-mediainfo' ),
					'popular_items'              => __( 'Popular Audio Channels', 'cute-mediainfo' ),
					'search_items'               => __( 'Search Audio Channels', 'cute-mediainfo' ),
					'not_found'                  => __( 'Not Found', 'cute-mediainfo' ),
					'no_terms'                   => __( 'No Audio Channels', 'cute-mediainfo' ),
					'items_list'                 => __( 'Items list', 'cute-mediainfo' ),
					'items_list_navigation'      => __( 'Items list navigation', 'cute-mediainfo' ),
				),
				'hierarchical'       => false,
				'public'             => false,
				'show_ui'            => true,
				'show_in_quick_edit' => false,
				'show_admin_column'  => false,
				'show_in_nav_menus'  => false,
				'show_tagcloud'      => false,
				'rewrite'            => false,
				'show_in_rest'       => false,
				'meta_box_cb'        => false,
			),
		),

		'cutemi_audio_bitrate'      => array(
			'args' => array(
				'labels'             => array(
					'name'                       => _x( 'Audio Bitrate', 'Taxonomy General Name', 'cute-mediainfo' ),
					'singular_name'              => _x( 'Audio Bitrate', 'Taxonomy Singular Name', 'cute-mediainfo' ),
					'menu_name'                  => __( 'Audio Bitrates', 'cute-mediainfo' ),
					'all_items'                  => __( 'All Items', 'cute-mediainfo' ),
					'parent_item'                => __( 'Parent Audio Bitrate', 'cute-mediainfo' ),
					'parent_item_colon'          => __( 'Parent Audio Bitrate:', 'cute-mediainfo' ),
					'new_item_name'              => __( 'New Audio Bitrate Name', 'cute-mediainfo' ),
					'add_new_item'               => __( 'Add New Audio Bitrate', 'cute-mediainfo' ),
					'edit_item'                  => __( 'Edit Audio Bitrate', 'cute-mediainfo' ),
					'update_item'                => __( 'Update Audio Bitrate', 'cute-mediainfo' ),
					'view_item'                  => __( 'View Audio Bitrate', 'cute-mediainfo' ),
					'separate_items_with_commas' => __( 'Separate Audio Bitrates with commas', 'cute-mediainfo' ),
					'add_or_remove_items'        => __( 'Add or remove Audio Bitrates', 'cute-mediainfo' ),
					'choose_from_most_used'      => __( 'Choose from the most used', 'cute-mediainfo' ),
					'popular_items'              => __( 'Popular Audio Bitrates', 'cute-mediainfo' ),
					'search_items'               => __( 'Search Audio Bitrates', 'cute-mediainfo' ),
					'not_found'                  => __( 'Not Found', 'cute-mediainfo' ),
					'no_terms'                   => __( 'No Audio Bitrates', 'cute-mediainfo' ),
					'items_list'                 => __( 'Items list', 'cute-mediainfo' ),
					'items_list_navigation'      => __( 'Items list navigation', 'cute-mediainfo' ),
				),
				'hierarchical'       => false,
				'public'             => false,
				'show_ui'            => true,
				'show_in_quick_edit' => false,
				'show_admin_column'  => false,
				'show_in_nav_menus'  => false,
				'show_tagcloud'      => false,
				'rewrite'            => false,
				'show_in_rest'       => false,
				'meta_box_cb'        => false,
			),
		),

		'cutemi_audio_bitrate_mode' => array(
			'args' => array(
				'labels'             => array(
					'name'                       => _x( 'Audio Bitrate Mode', 'Taxonomy General Name', 'cute-mediainfo' ),
					'singular_name'              => _x( 'Audio Bitrate Mode', 'Taxonomy Singular Name', 'cute-mediainfo' ),
					'menu_name'                  => __( 'Audio Bitrate Modes', 'cute-mediainfo' ),
					'all_items'                  => __( 'All Items', 'cute-mediainfo' ),
					'parent_item'                => __( 'Parent Audio Bitrate Mode', 'cute-mediainfo' ),
					'parent_item_colon'          => __( 'Parent Audio Bitrate Mode:', 'cute-mediainfo' ),
					'new_item_name'              => __( 'New Audio Bitrate Mode Name', 'cute-mediainfo' ),
					'add_new_item'               => __( 'Add New Audio Bitrate Mode', 'cute-mediainfo' ),
					'edit_item'                  => __( 'Edit Audio Bitrate Mode', 'cute-mediainfo' ),
					'update_item'                => __( 'Update Audio Bitrate Mode', 'cute-mediainfo' ),
					'view_item'                  => __( 'View Audio Bitrate Mode', 'cute-mediainfo' ),
					'separate_items_with_commas' => __( 'Separate Audio Bitrate Modes with commas', 'cute-mediainfo' ),
					'add_or_remove_items'        => __( 'Add or remove Audio Bitrate Modes', 'cute-mediainfo' ),
					'choose_from_most_used'      => __( 'Choose from the most used', 'cute-mediainfo' ),
					'popular_items'              => __( 'Popular Audio Bitrate Modes', 'cute-mediainfo' ),
					'search_items'               => __( 'Search Audio Bitrate Modes', 'cute-mediainfo' ),
					'not_found'                  => __( 'Not Found', 'cute-mediainfo' ),
					'no_terms'                   => __( 'No Audio Bitrate Modes', 'cute-mediainfo' ),
					'items_list'                 => __( 'Items list', 'cute-mediainfo' ),
					'items_list_navigation'      => __( 'Items list navigation', 'cute-mediainfo' ),
				),
				'hierarchical'       => false,
				'public'             => false,
				'show_ui'            => true,
				'show_in_quick_edit' => false,
				'show_admin_column'  => false,
				'show_in_nav_menus'  => false,
				'show_tagcloud'      => false,
				'rewrite'            => false,
				'show_in_rest'       => false,
				'meta_box_cb'        => false,
			),
		),

		'cutemi_audio_langs'        => array(
			'args' => array(
				'labels'             => array(
					'name'                       => _x( 'Audio Language', 'Taxonomy General Name', 'cute-mediainfo' ),
					'singular_name'              => _x( 'Audio Language', 'Taxonomy Singular Name', 'cute-mediainfo' ),
					'menu_name'                  => __( 'Audio Languages', 'cute-mediainfo' ),
					'all_items'                  => __( 'All Audio Languages', 'cute-mediainfo' ),
					'parent_item'                => __( 'Parent Audio Language', 'cute-mediainfo' ),
					'parent_item_colon'          => __( 'Parent Audio Language:', 'cute-mediainfo' ),
					'new_item_name'              => __( 'New Audio Language Name', 'cute-mediainfo' ),
					'add_new_item'               => __( 'Add New Audio Language', 'cute-mediainfo' ),
					'edit_item'                  => __( 'Edit Audio Language', 'cute-mediainfo' ),
					'update_item'                => __( 'Update Audio Language', 'cute-mediainfo' ),
					'view_item'                  => __( 'View Audio Language', 'cute-mediainfo' ),
					'separate_items_with_commas' => __( 'Separate Audio Languages with commas', 'cute-mediainfo' ),
					'add_or_remove_items'        => __( 'Add or remove Audio Languages', 'cute-mediainfo' ),
					'choose_from_most_used'      => __( 'Choose from the most used', 'cute-mediainfo' ),
					'popular_items'              => __( 'Popular Audio Languages', 'cute-mediainfo' ),
					'search_items'               => __( 'Search Audio Languages', 'cute-mediainfo' ),
					'not_found'                  => __( 'Not Found', 'cute-mediainfo' ),
					'no_terms'                   => __( 'No Audio Languages', 'cute-mediainfo' ),
					'items_list'                 => __( 'Items list', 'cute-mediainfo' ),
					'items_list_navigation'      => __( 'Items list navigation', 'cute-mediainfo' ),
				),
				'hierarchical'       => true,
				'public'             => false,
				'show_ui'            => true,
				'show_in_quick_edit' => false,
				'show_admin_column'  => false,
				'show_in_nav_menus'  => false,
				'show_tagcloud'      => false,
				'rewrite'            => false,
				'show_in_rest'       => false,
				'meta_box_cb'        => false,
			),
		),

		'cutemi_file_format'        => array(
			'args' => array(
				'labels'             => array(
					'name'                       => _x( 'Video Format', 'Taxonomy General Name', 'cute-mediainfo' ),
					'singular_name'              => _x( 'Video Format', 'Taxonomy Singular Name', 'cute-mediainfo' ),
					'menu_name'                  => __( 'Video Formats', 'cute-mediainfo' ),
					'all_items'                  => __( 'All Video Formats', 'cute-mediainfo' ),
					'parent_item'                => __( 'Parent Video Format', 'cute-mediainfo' ),
					'parent_item_colon'          => __( 'Parent Video Format:', 'cute-mediainfo' ),
					'new_item_name'              => __( 'New Video Format Name', 'cute-mediainfo' ),
					'add_new_item'               => __( 'Add New Video Format', 'cute-mediainfo' ),
					'edit_item'                  => __( 'Edit Video Format', 'cute-mediainfo' ),
					'update_item'                => __( 'Update Video Format', 'cute-mediainfo' ),
					'view_item'                  => __( 'View Video Format', 'cute-mediainfo' ),
					'separate_items_with_commas' => __( 'Separate Video Formats with commas', 'cute-mediainfo' ),
					'add_or_remove_items'        => __( 'Add or remove Video Formats', 'cute-mediainfo' ),
					'choose_from_most_used'      => __( 'Choose from the most used', 'cute-mediainfo' ),
					'popular_items'              => __( 'Popular Video Formats', 'cute-mediainfo' ),
					'search_items'               => __( 'Search Video Formats', 'cute-mediainfo' ),
					'not_found'                  => __( 'Not Found', 'cute-mediainfo' ),
					'no_terms'                   => __( 'No Video Formats', 'cute-mediainfo' ),
					'items_list'                 => __( 'Items list', 'cute-mediainfo' ),
					'items_list_navigation'      => __( 'Items list navigation', 'cute-mediainfo' ),
				),
				'hierarchical'       => false,
				'public'             => false,
				'show_ui'            => true,
				'show_in_quick_edit' => false,
				'show_admin_column'  => false,
				'show_in_nav_menus'  => false,
				'show_tagcloud'      => false,
				'rewrite'            => false,
				'show_in_rest'       => false,
				'meta_box_cb'        => false,
			),
		),

		'cutemi_video_tech'         => array(
			'args' => array(
				'labels'             => array(
					'name'                       => _x( 'Video Tech', 'Taxonomy General Name', 'cute-mediainfo' ),
					'singular_name'              => _x( 'Video Tech', 'Taxonomy Singular Name', 'cute-mediainfo' ),
					'menu_name'                  => __( 'Video Techs', 'cute-mediainfo' ),
					'all_items'                  => __( 'All Video Techs', 'cute-mediainfo' ),
					'parent_item'                => __( 'Parent Video Tech', 'cute-mediainfo' ),
					'parent_item_colon'          => __( 'Parent Video Tech:', 'cute-mediainfo' ),
					'new_item_name'              => __( 'New Video Tech Name', 'cute-mediainfo' ),
					'add_new_item'               => __( 'Add New Video Tech', 'cute-mediainfo' ),
					'edit_item'                  => __( 'Edit Video Tech', 'cute-mediainfo' ),
					'update_item'                => __( 'Update Video Tech', 'cute-mediainfo' ),
					'view_item'                  => __( 'View Video Tech', 'cute-mediainfo' ),
					'separate_items_with_commas' => __( 'Separate Video Techs with commas', 'cute-mediainfo' ),
					'add_or_remove_items'        => __( 'Add or remove Video Techs', 'cute-mediainfo' ),
					'choose_from_most_used'      => __( 'Choose from the most used', 'cute-mediainfo' ),
					'popular_items'              => __( 'Popular Video Techs', 'cute-mediainfo' ),
					'search_items'               => __( 'Search Video Techs', 'cute-mediainfo' ),
					'not_found'                  => __( 'Not Found', 'cute-mediainfo' ),
					'no_terms'                   => __( 'No Video Techs', 'cute-mediainfo' ),
					'items_list'                 => __( 'Items list', 'cute-mediainfo' ),
					'items_list_navigation'      => __( 'Items list navigation', 'cute-mediainfo' ),
				),
				'hierarchical'       => true,
				'public'             => false,
				'show_ui'            => true,
				'show_in_quick_edit' => false,
				'show_admin_column'  => false,
				'show_in_nav_menus'  => false,
				'show_tagcloud'      => false,
				'rewrite'            => false,
				'show_in_rest'       => false,
				'meta_box_cb'        => false,
			),
		),

		'cutemi_text_langs'         => array(
			'args' => array(
				'labels'             => array(
					'name'                       => _x( 'Text Language', 'Taxonomy General Name', 'cute-mediainfo' ),
					'singular_name'              => _x( 'Text Language', 'Taxonomy Singular Name', 'cute-mediainfo' ),
					'menu_name'                  => __( 'Text Languages', 'cute-mediainfo' ),
					'all_items'                  => __( 'All Text Languages', 'cute-mediainfo' ),
					'parent_item'                => __( 'Parent Text Language', 'cute-mediainfo' ),
					'parent_item_colon'          => __( 'Parent Text Language:', 'cute-mediainfo' ),
					'new_item_name'              => __( 'New Text Language Name', 'cute-mediainfo' ),
					'add_new_item'               => __( 'Add New Text Language', 'cute-mediainfo' ),
					'edit_item'                  => __( 'Edit Text Language', 'cute-mediainfo' ),
					'update_item'                => __( 'Update Text Language', 'cute-mediainfo' ),
					'view_item'                  => __( 'View Text Language', 'cute-mediainfo' ),
					'separate_items_with_commas' => __( 'Separate Text Languages with commas', 'cute-mediainfo' ),
					'add_or_remove_items'        => __( 'Add or remove Text Languages', 'cute-mediainfo' ),
					'choose_from_most_used'      => __( 'Choose from the most used', 'cute-mediainfo' ),
					'popular_items'              => __( 'Popular Text Languages', 'cute-mediainfo' ),
					'search_items'               => __( 'Search Text Languages', 'cute-mediainfo' ),
					'not_found'                  => __( 'Not Found', 'cute-mediainfo' ),
					'no_terms'                   => __( 'No Text Languages', 'cute-mediainfo' ),
					'items_list'                 => __( 'Items list', 'cute-mediainfo' ),
					'items_list_navigation'      => __( 'Items list navigation', 'cute-mediainfo' ),
				),
				'hierarchical'       => true,
				'public'             => false,
				'show_ui'            => true,
				'show_in_quick_edit' => false,
				'show_admin_column'  => false,
				'show_in_nav_menus'  => false,
				'show_tagcloud'      => false,
				'rewrite'            => false,
				'show_in_rest'       => false,
				'meta_box_cb'        => false,
			),
		),
		'cutemi_text_format'        => array(
			'args' => array(
				'labels'             => array(
					'name'                       => _x( 'Text Format', 'Taxonomy General Name', 'cute-mediainfo' ),
					'singular_name'              => _x( 'Text Format', 'Taxonomy Singular Name', 'cute-mediainfo' ),
					'menu_name'                  => __( 'Text Formats', 'cute-mediainfo' ),
					'all_items'                  => __( 'All Text Formats', 'cute-mediainfo' ),
					'parent_item'                => __( 'Parent Text Format', 'cute-mediainfo' ),
					'parent_item_colon'          => __( 'Parent Text Format:', 'cute-mediainfo' ),
					'new_item_name'              => __( 'New Text Format Name', 'cute-mediainfo' ),
					'add_new_item'               => __( 'Add New Text Format', 'cute-mediainfo' ),
					'edit_item'                  => __( 'Edit Text Format', 'cute-mediainfo' ),
					'update_item'                => __( 'Update Text Format', 'cute-mediainfo' ),
					'view_item'                  => __( 'View Text Format', 'cute-mediainfo' ),
					'separate_items_with_commas' => __( 'Separate Text Formats with commas', 'cute-mediainfo' ),
					'add_or_remove_items'        => __( 'Add or remove Text Formats', 'cute-mediainfo' ),
					'choose_from_most_used'      => __( 'Choose from the most used', 'cute-mediainfo' ),
					'popular_items'              => __( 'Popular Text Formats', 'cute-mediainfo' ),
					'search_items'               => __( 'Search Text Formats', 'cute-mediainfo' ),
					'not_found'                  => __( 'Not Found', 'cute-mediainfo' ),
					'no_terms'                   => __( 'No Text Formats', 'cute-mediainfo' ),
					'items_list'                 => __( 'Items list', 'cute-mediainfo' ),
					'items_list_navigation'      => __( 'Items list navigation', 'cute-mediainfo' ),
				),
				'hierarchical'       => true,
				'public'             => false,
				'show_ui'            => true,
				'show_in_quick_edit' => false,
				'show_admin_column'  => false,
				'show_in_nav_menus'  => false,
				'show_tagcloud'      => false,
				'rewrite'            => false,
				'show_in_rest'       => false,
				'meta_box_cb'        => false,
			),
		),
		'cutemi_text_type'          => array(
			'args' => array(
				'labels'             => array(
					'name'                       => _x( 'Text Type', 'Taxonomy General Name', 'cute-mediainfo' ),
					'singular_name'              => _x( 'Text Type', 'Taxonomy Singular Name', 'cute-mediainfo' ),
					'menu_name'                  => __( 'Text Types', 'cute-mediainfo' ),
					'all_items'                  => __( 'All Text Types', 'cute-mediainfo' ),
					'parent_item'                => __( 'Parent Text Type', 'cute-mediainfo' ),
					'parent_item_colon'          => __( 'Parent Text Type:', 'cute-mediainfo' ),
					'new_item_name'              => __( 'New Text Type Name', 'cute-mediainfo' ),
					'add_new_item'               => __( 'Add New Text Type', 'cute-mediainfo' ),
					'edit_item'                  => __( 'Edit Text Type', 'cute-mediainfo' ),
					'update_item'                => __( 'Update Text Type', 'cute-mediainfo' ),
					'view_item'                  => __( 'View Text Type', 'cute-mediainfo' ),
					'separate_items_with_commas' => __( 'Separate Text Types with commas', 'cute-mediainfo' ),
					'add_or_remove_items'        => __( 'Add or remove Text Types', 'cute-mediainfo' ),
					'choose_from_most_used'      => __( 'Choose from the most used', 'cute-mediainfo' ),
					'popular_items'              => __( 'Popular Text Types', 'cute-mediainfo' ),
					'search_items'               => __( 'Search Text Types', 'cute-mediainfo' ),
					'not_found'                  => __( 'Not Found', 'cute-mediainfo' ),
					'no_terms'                   => __( 'No Text Types', 'cute-mediainfo' ),
					'items_list'                 => __( 'Items list', 'cute-mediainfo' ),
					'items_list_navigation'      => __( 'Items list navigation', 'cute-mediainfo' ),
				),
				'hierarchical'       => false,
				'public'             => false,
				'show_ui'            => true,
				'show_in_quick_edit' => false,
				'show_admin_column'  => false,
				'show_in_nav_menus'  => false,
				'show_tagcloud'      => false,
				'rewrite'            => false,
				'show_in_rest'       => false,
				'meta_box_cb'        => false,
			),
		),
	);

	$taxonomies_wp_cute_mediainfo = apply_filters( 'cutemi_taxonomies_pre_register', $taxonomies_wp_cute_mediainfo );
	$order                        = array(
		'cutemi_site_source',
		'cutemi_file_format',
		'cutemi_video_tech',
		'cutemi_video_resolution',
		'cutemi_video_bitrate',
		'cutemi_video_bitrate_mode',
		'cutemi_audio_tech',
		'cutemi_audio_channels',
		'cutemi_audio_bitrate',
		'cutemi_audio_bitrate_mode',
		'cutemi_audio_langs',
		'cutemi_text_format',
		'cutemi_text_langs',
		'cutemi_text_type',
	);

	$order = apply_filters( 'cutemi_taxonomies_order_pre_register', $order, $taxonomies_wp_cute_mediainfo );
	foreach ( $order as $tax_name ) {
		if ( ! taxonomy_exists( $tax_name ) ) {
			$args                 = $taxonomies_wp_cute_mediainfo[ $tax_name ]['args'];
			$args['capabilities'] = array(
				'manage_terms' => 'manage_categories',
				'edit_terms'   => 'manage_categories',
				'delete_terms' => 'cutemi_delete_term', //disable delete
				'assign_terms' => 'edit_posts',
			);
			register_taxonomy( $tax_name, null, $args );
		}
	}

}

add_action( 'init', 'cutemi_register_taxonomies' );

